"""Bit-perfect regression tests for bslz4/bszstd C functions.

Tests all enginexdtypexshapexdistribution combinations against
pure-numpy reference. Also compares against original bslz4_to_sparse
f2py output when available.

Test data is generated by make_bs_testdata.py if not present.
"""

import os
import sys
import numpy as np
import pytest
import c2ImageD11._cImageD11 as _m

_BSLZ4_PY2_SKIP = sys.version_info[0] < 3

TESTDATA_LZ4 = os.path.join(os.path.dirname(__file__), "bslz4_testdata.h5")
TESTDATA_ZSTD = os.path.join(os.path.dirname(__file__), "bszstd_testdata.h5")


# =============================================================================
# Helpers
# =============================================================================

def _ensure_testdata():
    """Generate test data if not present."""
    if not os.path.exists(TESTDATA_LZ4) or not os.path.exists(TESTDATA_ZSTD):
        script = os.path.join(os.path.dirname(__file__), "make_bs_testdata.py")
        if os.path.exists(script):
            os.system("python3 " + script + " --zstd")


def _pysparse(frame, mask, cut):
    """Pure-numpy reference: apply mask, threshold, return (values, indices)."""
    masked = frame * mask
    pixels = masked > cut
    if not pixels.any():
        return np.zeros(0, dtype=frame.dtype), np.zeros(0, dtype=np.uint32)
    return masked[pixels], np.where(pixels.ravel())[0].astype(np.uint32)


def _pysparse_csc(frame, mask, cut, data, indices, indptr, out):
    """Pure-numpy reference for CSC: sparse output + dot product."""
    vals, idxs = _pysparse(frame, mask, cut)
    out[:] = 0.0
    for j in range(len(frame.ravel())):
        v = frame.ravel()[j] * mask.ravel()[j]
        if v > 0:
            for k in range(indptr[j], indptr[j + 1]):
                out[indices[k]] += float(data[k]) * float(v)
    return vals, idxs


# =============================================================================
# Smoke tests
# =============================================================================

class TestBslz4Smoke:
    """Basic buffer protocol tests for all 12 Python-facing functions."""

    @pytest.mark.parametrize("func,dtype", [
        (_m.bslz4_u8,  np.uint8),
        (_m.bslz4_u16, np.uint16),
        (_m.bslz4_u32, np.uint32),
    ])
    def test_bslz4_basic(self, func, dtype):
        compressed = np.zeros(100, dtype=np.uint8)
        mask = np.ones(4, dtype=np.uint8)
        out = np.zeros(4, dtype=dtype)
        outP = np.zeros(4, dtype=np.uint32)
        offs = np.array([0], dtype=np.int64)
        lens = np.array([len(compressed)], dtype=np.int32)
        npc  = np.zeros(1, dtype=np.int32)
        npx = func(compressed, mask, out, outP, 0, offs, lens, npc)
        assert isinstance(npx, int)

    @pytest.mark.parametrize("func,dtype", [
        (_m.bslz4_csc_u8,  np.uint8),
        (_m.bslz4_csc_u16, np.uint16),
        (_m.bslz4_csc_u32, np.uint32),
    ])
    def test_bslz4_csc(self, func, dtype):
        compressed = np.zeros(100, dtype=np.uint8)
        mask = np.ones(4, dtype=np.uint8)
        outpx = np.zeros(4, dtype=dtype)
        outP = np.zeros(4, dtype=np.uint32)
        out = np.zeros(8, dtype=np.float64)
        data = np.ones(4, dtype=np.float32)
        indices = np.zeros(4, dtype=np.uint32)
        indptr = np.arange(5, dtype=np.uint32)
        offs = np.array([0], dtype=np.int64)
        lens = np.array([len(compressed)], dtype=np.int32)
        npc  = np.zeros(1, dtype=np.int32)
        npx = func(compressed, mask, outpx, outP, 0, out, data, indices, indptr,
                   offs, lens, npc)
        assert isinstance(npx, int)

    @pytest.mark.parametrize("func,dtype", [
        (_m.bszstd_u8,  np.uint8),
        (_m.bszstd_u16, np.uint16),
        (_m.bszstd_u32, np.uint32),
    ])
    def test_bszstd_basic(self, func, dtype):
        compressed = np.zeros(100, dtype=np.uint8)
        mask = np.ones(4, dtype=np.uint8)
        out = np.zeros(4, dtype=dtype)
        outP = np.zeros(4, dtype=np.uint32)
        offs = np.array([0], dtype=np.int64)
        lens = np.array([len(compressed)], dtype=np.int32)
        npc  = np.zeros(1, dtype=np.int32)
        npx = func(compressed, mask, out, outP, 0, offs, lens, npc)
        assert isinstance(npx, int)

    @pytest.mark.parametrize("func,dtype", [
        (_m.bszstd_csc_u8,  np.uint8),
        (_m.bszstd_csc_u16, np.uint16),
        (_m.bszstd_csc_u32, np.uint32),
    ])
    def test_bszstd_csc(self, func, dtype):
        compressed = np.zeros(100, dtype=np.uint8)
        mask = np.ones(4, dtype=np.uint8)
        outpx = np.zeros(4, dtype=dtype)
        outP = np.zeros(4, dtype=np.uint32)
        out = np.zeros(8, dtype=np.float64)
        data = np.ones(4, dtype=np.float32)
        indices = np.zeros(4, dtype=np.uint32)
        indptr = np.arange(5, dtype=np.uint32)
        offs = np.array([0], dtype=np.int64)
        lens = np.array([len(compressed)], dtype=np.int32)
        npc  = np.zeros(1, dtype=np.int32)
        npx = func(compressed, mask, outpx, outP, 0, out, data, indices, indptr,
                   offs, lens, npc)
        assert isinstance(npx, int)


# =============================================================================
# Bit-perfect regression (requires test data + h5py + hdf5plugin)
# =============================================================================

@pytest.mark.skipif(
    _BSLZ4_PY2_SKIP,
    reason="bslz4 tests not yet working on Python 2.7"
)
@pytest.mark.skipif(
    not os.path.exists(TESTDATA_LZ4),
    reason="run 'python3 tests/make_bs_testdata.py --zstd' first"
)
class TestBitPerfectLZ4:
    """Compare bslz4_* output against pure-numpy reference for LZ4 data."""

    ENGINES = {
        "lz4": {"basic": {np.uint8: _m.bslz4_u8, np.uint16: _m.bslz4_u16, np.uint32: _m.bslz4_u32},
                "csc":   {np.uint8: _m.bslz4_csc_u8, np.uint16: _m.bslz4_csc_u16, np.uint32: _m.bslz4_csc_u32}},
    }

    def _datasets(self):
        h5py = pytest.importorskip("h5py")
        hdf5plugin = pytest.importorskip("hdf5plugin")  # noqa
        with h5py.File(TESTDATA_LZ4, "r") as f:
            return [(name, f[name].shape, f[name].dtype) for name in sorted(f.keys())]

    def _test_dataset(self, ds_info, engine, cut=0):
        name, shape, dtype = ds_info
        dtype = np.dtype(dtype).type
        h5py = pytest.importorskip("h5py")
        mask = np.ones(shape[1:], dtype=np.uint8)
        nframes = min(shape[0], 4)

        func = self.ENGINES[engine]["basic"][dtype]
        N = mask.size
        vals = np.empty(N, dtype=dtype)
        inds = np.empty(N, dtype=np.uint32)

        with h5py.File(TESTDATA_LZ4, "r") as f:
            ds = f[name]
            for frame in range(nframes):
                ref_vals, ref_inds = _pysparse(ds[frame], mask, cut)
                chunk_info, chunk = ds.id.read_direct_chunk((frame, 0, 0))
                offs = np.array([0], dtype=np.int64)
                lens = np.array([len(chunk)], dtype=np.int32)
                npc  = np.zeros(1, dtype=np.int32)
                npx = func(chunk, mask.ravel(), vals, inds, cut,
                           offs, lens, npc)
                assert npx == len(ref_vals), \
                    "npx mismatch: %d vs %d at frame=%d cut=%d" % (npx, len(ref_vals), frame, cut)
                np.testing.assert_array_equal(vals[:npx], ref_vals,
                    err_msg="values mismatch at frame=%d cut=%d" % (frame, cut))
                np.testing.assert_array_equal(inds[:npx], ref_inds,
                    err_msg="indices mismatch at frame=%d cut=%d" % (frame, cut))
        
    def _test_dataset_csc(self, ds_info, engine, cut=0):
        name, shape, dtype = ds_info
        dtype = np.dtype(dtype).type
        h5py = pytest.importorskip("h5py")
        mask = np.ones(shape[1:], dtype=np.uint8)
        flat = mask.ravel()
        func = self.ENGINES[engine]["csc"][dtype]
        N = flat.size

        data = np.ones(N, dtype=np.float32)
        indices = np.zeros(N, dtype=np.uint32)
        indptr = np.arange(N + 1, dtype=np.uint32)
        outpx = np.empty(N, dtype=dtype)
        outP = np.empty(N, dtype=np.uint32)
        powder = np.zeros(1, dtype=np.float64)
        powder_ref = np.zeros(1, dtype=np.float64)

        with h5py.File(TESTDATA_LZ4, "r") as f:
            ds = f[name]
            for frame in range(min(shape[0], 2)):
                ref_vals, ref_inds = _pysparse_csc(ds[frame], mask, cut,
                                                   data, indices, indptr, powder_ref)
                chunk_info, chunk = ds.id.read_direct_chunk((frame, 0, 0))
                offs = np.array([0], dtype=np.int64)
                lens = np.array([len(chunk)], dtype=np.int32)
                npc  = np.zeros(1, dtype=np.int32)
                npx = func(chunk, flat, outpx, outP, cut,
                          powder, data, indices, indptr,
                          offs, lens, npc)
                assert npx == len(ref_vals), "CSC npx mismatch frame=%d" % frame
                np.testing.assert_array_equal(outpx[:npx], ref_vals,
                    err_msg="CSC values mismatch frame=%d" % frame)
                np.testing.assert_array_equal(outP[:npx], ref_inds,
                    err_msg="CSC indices mismatch frame=%d" % frame)
                np.testing.assert_allclose(powder, powder_ref, rtol=1e-10,
                    err_msg="CSC powder mismatch frame=%d" % frame)

    def test_lz4_basic_all_datasets(self):
        for ds_info in self._datasets():
            self._test_dataset(ds_info, "lz4", 0)
            self._test_dataset(ds_info, "lz4", 10)

    def test_lz4_csc_all_datasets(self):
        for ds_info in self._datasets():
            self._test_dataset_csc(ds_info, "lz4", 0)
            self._test_dataset_csc(ds_info, "lz4", 10)


@pytest.mark.skipif(
    _BSLZ4_PY2_SKIP,
    reason="bslz4 tests not yet working on Python 2.7"
)
@pytest.mark.skipif(
    not os.path.exists(TESTDATA_ZSTD),
    reason="run 'python3 tests/make_bs_testdata.py --zstd' first"
)
class TestBitPerfectZSTD:
    """Compare bszstd_* output against pure-numpy reference for ZSTD data."""

    FUNCS = {
        "basic": {np.uint8: _m.bszstd_u8, np.uint16: _m.bszstd_u16, np.uint32: _m.bszstd_u32},
        "csc":   {np.uint8: _m.bszstd_csc_u8, np.uint16: _m.bszstd_csc_u16, np.uint32: _m.bszstd_csc_u32},
    }

    def _datasets(self):
        h5py = pytest.importorskip("h5py")
        hdf5plugin = pytest.importorskip("hdf5plugin")  # noqa
        with h5py.File(TESTDATA_ZSTD, "r") as f:
            return [(name, f[name].shape, f[name].dtype) for name in sorted(f.keys())]

    def test_zstd_basic(self):
        for name, shape, dtype in self._datasets():
            dtype = np.dtype(dtype).type
            h5py = pytest.importorskip("h5py")
            mask = np.ones(shape[1:], dtype=np.uint8)
            func = self.FUNCS["basic"][dtype]
            N = mask.size
            vals = np.empty(N, dtype=dtype)
            inds = np.empty(N, dtype=np.uint32)

            with h5py.File(TESTDATA_ZSTD, "r") as f:
                ds = f[name]
                for frame in range(min(shape[0], 2)):
                    ref_vals, ref_inds = _pysparse(ds[frame], mask, 0)
                    chunk_info, chunk = ds.id.read_direct_chunk((frame, 0, 0))
                    chunk_buf = chunk
                    offs_l = np.array([0], dtype=np.int64)
                    lens_l = np.array([len(chunk)], dtype=np.int32)
                    npc_l  = np.zeros(1, dtype=np.int32)
                    npx = func(chunk, mask.ravel(), vals, inds, 0,
                               offs_l, lens_l, npc_l)
                    assert npx == len(ref_vals)
                    np.testing.assert_array_equal(vals[:npx], ref_vals)
                    np.testing.assert_array_equal(inds[:npx], ref_inds)


# =============================================================================
# Equivalence vs original bslz4_to_sparse f2py
# =============================================================================

@pytest.mark.skipif(
    _BSLZ4_PY2_SKIP,
    reason="bslz4 tests not yet working on Python 2.7"
)
class TestF2pyEquivalence:
    """Compare c2ImageD11 output against original f2py extension."""

    def test_lz4_u16_c_layer(self):
        """Compare bslz4_u16 C function directly with the f2py version."""
        try:
            from bslz4_to_sparse import bslz4_uint16_t as f2py_fn
        except ImportError:
            pytest.skip("original bslz4_to_sparse not installed")

        h5py = pytest.importorskip("h5py")
        hdf5plugin = pytest.importorskip("hdf5plugin")  # noqa

        # Use the eiger data if available
        SRC = "/home/worker/test_data/eiger_lz4_u16.h5"
        if not os.path.exists(SRC):
            SRC = "/home/worker/test_data/eiger_0000.h5"
        if not os.path.exists(SRC):
            pytest.skip("no test data file found")

        with h5py.File(SRC, "r") as f:
            ds = f["/entry_0000/measurement/data"]
            mask = np.ones(ds.shape[1:], dtype=np.uint8)
            N = mask.size
            vals1 = np.empty(N, dtype=np.uint16)
            inds1 = np.empty(N, dtype=np.uint32)
            vals2 = np.empty(N, dtype=np.uint16)
            inds2 = np.empty(N, dtype=np.uint32)

            nframes = min(ds.shape[0], 10)
            for i in range(nframes):
                _, chunk = ds.id.read_direct_chunk((i, 0, 0))

                npx1 = f2py_fn(np.frombuffer(chunk, np.uint8), mask.ravel(), vals1, inds1, 0)
                offs2 = np.array([0], dtype=np.int64)
                lens2 = np.array([len(chunk)], dtype=np.int32)
                npc2  = np.zeros(1, dtype=np.int32)
                npx2 = _m.bslz4_u16(chunk, mask.ravel(), vals2, inds2, 0,
                                    offs2, lens2, npc2)

                assert npx1 == npx2, "frame %d: npx mismatch" % i
                np.testing.assert_array_equal(vals1[:npx1], vals2[:npx2],
                    err_msg="frame %d: values mismatch" % i)
                np.testing.assert_array_equal(inds1[:npx1], inds2[:npx2],
                    err_msg="frame %d: indices mismatch" % i)

    def test_lz4_csc_u16_c_layer(self):
        """Compare bslz4_csc_u16 with original f2py version."""
        try:
            from bslz4_to_sparse import bslz4_csc_uint16_t as f2py_fn
        except ImportError:
            pytest.skip("original bslz4_to_sparse not installed")

        h5py = pytest.importorskip("h5py")
        hdf5plugin = pytest.importorskip("hdf5plugin")  # noqa

        SRC = "/home/worker/test_data/eiger_lz4_u16.h5"
        if not os.path.exists(SRC):
            SRC = "/home/worker/test_data/eiger_0000.h5"
        if not os.path.exists(SRC):
            pytest.skip("no test data file found")

        with h5py.File(SRC, "r") as f:
            ds = f["/entry_0000/measurement/data"]
            mask = np.ones(ds.shape[1:], dtype=np.uint8)
            flat = mask.ravel()
            N = flat.size

            data = np.ones(N, dtype=np.float32)
            indices = np.zeros(N, dtype=np.uint32)
            indptr = np.arange(N + 1, dtype=np.uint32)
            outpx1 = np.empty(N, dtype=np.uint16)
            outP1 = np.empty(N, dtype=np.uint32)
            powder1 = np.zeros(1, dtype=np.float64)
            outpx2 = np.empty(N, dtype=np.uint16)
            outP2 = np.empty(N, dtype=np.uint32)
            powder2 = np.zeros(1, dtype=np.float64)

            for i in range(min(ds.shape[0], 5)):
                _, chunk = ds.id.read_direct_chunk((i, 0, 0))

                npx1 = f2py_fn(np.frombuffer(chunk, np.uint8), flat, outpx1, outP1, 0,
                               powder1, data, indices, indptr)
                offs2 = np.array([0], dtype=np.int64)
                lens2 = np.array([len(chunk)], dtype=np.int32)
                npc2  = np.zeros(1, dtype=np.int32)
                npx2 = _m.bslz4_csc_u16(chunk, flat, outpx2, outP2, 0,
                                        powder2, data, indices, indptr,
                                        offs2, lens2, npc2)

                assert npx1 == npx2, "frame %d: npx mismatch" % i
                np.testing.assert_array_equal(outpx1[:npx1], outpx2[:npx2])
                np.testing.assert_array_equal(outP1[:npx1], outP2[:npx2])
                np.testing.assert_allclose(powder1, powder2, rtol=1e-10)


# =============================================================================
# Integer CSC exact arithmetic tests
# =============================================================================

# Map pixel dtype -> CSC function dict (csc_itemsize -> function)
_INT_CSC_FUNCS = {
    np.uint8:  {1: _m.bslz4_csc_u8_cu8,  2: _m.bslz4_csc_u8_cu16,  4: _m.bslz4_csc_u8_cu32},
    np.uint16: {1: _m.bslz4_csc_u16_cu8, 2: _m.bslz4_csc_u16_cu16, 4: _m.bslz4_csc_u16_cu32},
    np.uint32: {1: _m.bslz4_csc_u32_cu8, 2: _m.bslz4_csc_u32_cu16, 4: _m.bslz4_csc_u32_cu32},
}

_ZSTD_INT_CSC_FUNCS = {
    np.uint8:  {1: _m.bszstd_csc_u8_cu8,  2: _m.bszstd_csc_u8_cu16,  4: _m.bszstd_csc_u8_cu32},
    np.uint16: {1: _m.bszstd_csc_u16_cu8, 2: _m.bszstd_csc_u16_cu16, 4: _m.bszstd_csc_u16_cu32},
    np.uint32: {1: _m.bszstd_csc_u32_cu8, 2: _m.bszstd_csc_u32_cu16, 4: _m.bszstd_csc_u32_cu32},
}


def _pysparse_csc_int(frame, mask, cut, data, indices, indptr, out):
    """Pure-numpy reference for integer CSC: uses uint64 for output."""
    vals, idxs = _pysparse(frame, mask, cut)
    out[:] = 0
    for j in range(len(frame.ravel())):
        v = frame.ravel()[j] * mask.ravel()[j]
        if v > 0:
            for k in range(indptr[j], indptr[j + 1]):
                out[indices[k]] += np.uint64(data[k]) * np.uint64(v)
    return vals, idxs


class TestIntegerCSCSmoke:
    """Smoke tests for integer CSC functions (all pixel x CSC type combos)."""

    @pytest.mark.parametrize("func,dtype,csc_dtype", [
        (_m.bslz4_csc_u8_cu8,   np.uint8,  np.uint8),
        (_m.bslz4_csc_u8_cu16,  np.uint8,  np.uint16),
        (_m.bslz4_csc_u8_cu32,  np.uint8,  np.uint32),
        (_m.bslz4_csc_u16_cu8,  np.uint16, np.uint8),
        (_m.bslz4_csc_u16_cu16, np.uint16, np.uint16),
        (_m.bslz4_csc_u16_cu32, np.uint16, np.uint32),
        (_m.bslz4_csc_u32_cu8,  np.uint32, np.uint8),
        (_m.bslz4_csc_u32_cu16, np.uint32, np.uint16),
        (_m.bslz4_csc_u32_cu32, np.uint32, np.uint32),
        (_m.bszstd_csc_u8_cu8,   np.uint8,  np.uint8),
        (_m.bszstd_csc_u8_cu16,  np.uint8,  np.uint16),
        (_m.bszstd_csc_u8_cu32,  np.uint8,  np.uint32),
        (_m.bszstd_csc_u16_cu8,  np.uint16, np.uint8),
        (_m.bszstd_csc_u16_cu16, np.uint16, np.uint16),
        (_m.bszstd_csc_u16_cu32, np.uint16, np.uint32),
        (_m.bszstd_csc_u32_cu8,  np.uint32, np.uint8),
        (_m.bszstd_csc_u32_cu16, np.uint32, np.uint16),
        (_m.bszstd_csc_u32_cu32, np.uint32, np.uint32),
    ])
    def test_smoke(self, func, dtype, csc_dtype):
        """Each integer CSC function accepts correct buffer types."""
        compressed = np.zeros(100, dtype=np.uint8)
        mask = np.ones(4, dtype=np.uint8)
        outpx = np.zeros(4, dtype=dtype)
        outP = np.zeros(4, dtype=np.uint32)
        out = np.zeros(8, dtype=np.uint64)
        data = np.ones(4, dtype=csc_dtype)
        indices = np.zeros(4, dtype=np.uint32)
        indptr = np.arange(5, dtype=np.uint32)
        offs = np.array([0], dtype=np.int64)
        lens = np.array([len(compressed)], dtype=np.int32)
        npc  = np.zeros(1, dtype=np.int32)
        npx = func(compressed, mask, outpx, outP, 0, out, data, indices, indptr,
                   offs, lens, npc)
        assert isinstance(npx, int)

    @pytest.mark.parametrize("func,dtype,csc_dtype", [
        (_m.bslz4_csc_u8_cu8,   np.uint8,  np.uint8),
        (_m.bslz4_csc_u8_cu16,  np.uint8,  np.uint16),
        (_m.bslz4_csc_u8_cu32,  np.uint8,  np.uint32),
        (_m.bslz4_csc_u16_cu8,  np.uint16, np.uint8),
        (_m.bslz4_csc_u16_cu16, np.uint16, np.uint16),
        (_m.bslz4_csc_u16_cu32, np.uint16, np.uint32),
        (_m.bslz4_csc_u32_cu8,  np.uint32, np.uint8),
        (_m.bslz4_csc_u32_cu16, np.uint32, np.uint16),
        (_m.bslz4_csc_u32_cu32, np.uint32, np.uint32),
    ])
    def test_wrong_output_dtype_fails(self, func, dtype, csc_dtype):
        """Passing float64 output to integer CSC function should fail."""
        compressed = np.zeros(100, dtype=np.uint8)
        mask = np.ones(4, dtype=np.uint8)
        outpx = np.zeros(4, dtype=dtype)
        outP = np.zeros(4, dtype=np.uint32)
        out = np.zeros(8, dtype=np.float64)
        data = np.ones(4, dtype=csc_dtype)
        indices = np.zeros(4, dtype=np.uint32)
        indptr = np.arange(5, dtype=np.uint32)
        offs = np.array([0], dtype=np.int64)
        lens = np.array([len(compressed)], dtype=np.int32)
        npc  = np.zeros(1, dtype=np.int32)
        with pytest.raises((TypeError, RuntimeError, ValueError)):
            func(compressed, mask, outpx, outP, 0, out, data, indices, indptr,
                 offs, lens, npc)

    @pytest.mark.parametrize("func,dtype,csc_dtype", [
        (_m.bslz4_csc_u8_cu8,   np.uint8,  np.uint8),
        (_m.bslz4_csc_u8_cu16,  np.uint8,  np.uint16),
        (_m.bslz4_csc_u8_cu32,  np.uint8,  np.uint32),
        (_m.bslz4_csc_u16_cu8,  np.uint16, np.uint8),
        (_m.bslz4_csc_u16_cu16, np.uint16, np.uint16),
        (_m.bslz4_csc_u16_cu32, np.uint16, np.uint32),
        (_m.bslz4_csc_u32_cu8,  np.uint32, np.uint8),
        (_m.bslz4_csc_u32_cu16, np.uint32, np.uint16),
        (_m.bslz4_csc_u32_cu32, np.uint32, np.uint32),
    ])
    def test_wrong_data_dtype_fails(self, func, dtype, csc_dtype):
        """Passing float CSC data to integer CSC function should fail."""
        compressed = np.zeros(100, dtype=np.uint8)
        mask = np.ones(4, dtype=np.uint8)
        outpx = np.zeros(4, dtype=dtype)
        outP = np.zeros(4, dtype=np.uint32)
        out = np.zeros(8, dtype=np.uint64)
        data = np.ones(4, dtype=np.float32)
        indices = np.zeros(4, dtype=np.uint32)
        indptr = np.arange(5, dtype=np.uint32)
        offs = np.array([0], dtype=np.int64)
        lens = np.array([len(compressed)], dtype=np.int32)
        npc  = np.zeros(1, dtype=np.int32)
        with pytest.raises((TypeError, RuntimeError, ValueError)):
            func(compressed, mask, outpx, outP, 0, out, data, indices, indptr,
                 offs, lens, npc)


class TestIntegerCSCExact:
    """Verify integer CSC produces exact uint64 output (requires test data)."""

    @pytest.mark.skipif(
        not os.path.exists(TESTDATA_LZ4),
        reason="run 'python3 tests/make_bs_testdata.py --zstd' first"
    )
    @pytest.mark.parametrize("pixel_dtype,csc_dtype", [
        (np.uint16, np.uint8),
        (np.uint16, np.uint16),
        (np.uint16, np.uint32),
    ])
    def test_exact_vs_python(self, pixel_dtype, csc_dtype):
        """Integer CSC output matches pure-Python uint64 reference
        (uses u16 test dataset)."""
        h5py = pytest.importorskip("h5py")
        hdf5plugin = pytest.importorskip("hdf5plugin")  # noqa

        with h5py.File(TESTDATA_LZ4, "r") as f:
            # Find a u16 dataset
            ds_names = [k for k in f.keys() if "u16" in k]
            if not ds_names:
                # fall back to first dataset
                ds_info = sorted(f.keys())[0]
            else:
                ds_info = ds_names[0]
            shape = f[ds_info].shape
            ds = f[ds_info]
            mask = np.ones(shape[1:], dtype=np.uint8)
            flat = mask.ravel()
            N = flat.size

            data = np.ones(N, dtype=csc_dtype)
            indices = np.zeros(N, dtype=np.uint32)
            indptr = np.arange(N + 1, dtype=np.uint32)
            outpx = np.empty(N, dtype=np.uint16)
            outP = np.empty(N, dtype=np.uint32)
            powder = np.zeros(1, dtype=np.uint64)
            powder_ref = np.zeros(1, dtype=np.uint64)

            chunk_info, chunk = ds.id.read_direct_chunk((0, 0, 0))
            func = _INT_CSC_FUNCS[np.uint16][np.dtype(csc_dtype).itemsize]

            offs_c = np.array([0], dtype=np.int64)
            lens_c = np.array([len(chunk)], dtype=np.int32)
            npc_c  = np.zeros(1, dtype=np.int32)
            npx = func(chunk, flat, outpx, outP, 0,
                       powder, data, indices, indptr,
                       offs_c, lens_c, npc_c)
            _pysparse_csc_int(ds[0], mask, 0, data, indices,
                             indptr, powder_ref)

            assert npx > 0, "no pixels found"
            assert powder[0] == powder_ref[0], \
                "int CSC mismatch: %d vs %d (u16 pix, %s csc)" % (
                    powder[0], powder_ref[0], csc_dtype.__name__)


class TestChunk2sparseCSCInt:
    """Test chunk2sparseCSC auto-dispatch with integer CSC data."""

    def test_auto_dispatch_integer_csc(self):
        """chunk2sparseCSC with integer CSC data uses uint64 output."""
        from c2ImageD11.bslz4 import chunk2sparseCSC
        import numpy as np

        # Minimal mock CSC object
        class MockCSC(object):
            pass

        csc = MockCSC()
        mask = np.ones((2, 2), dtype=np.uint8)
        n = mask.size
        csc.data = np.ones(n, dtype=np.uint16)
        csc.indices = np.zeros(n, dtype=np.uint32)
        csc.indptr = np.arange(n + 1, dtype=np.uint32)
        csc.shape = (4,)

        dc = chunk2sparseCSC(mask, csc, dtype=np.uint16)
        assert dc.powder.dtype == np.uint64, \
            "powder dtype should be uint64, got %s" % dc.powder.dtype

    def test_auto_dispatch_float_csc(self):
        """chunk2sparseCSC with float CSC data uses float64 output (legacy)."""
        from c2ImageD11.bslz4 import chunk2sparseCSC
        import numpy as np

        class MockCSC(object):
            pass

        csc = MockCSC()
        mask = np.ones((2, 2), dtype=np.uint8)
        n = mask.size
        csc.data = np.ones(n, dtype=np.float32)
        csc.indices = np.zeros(n, dtype=np.uint32)
        csc.indptr = np.arange(n + 1, dtype=np.uint32)
        csc.shape = (4,)

        dc = chunk2sparseCSC(mask, csc, dtype=np.uint16)
        assert dc.powder.dtype == np.float64, \
            "powder dtype should be float64, got %s" % dc.powder.dtype


# =============================================================================
# Multi-chunk loop interchange tests
# =============================================================================

@pytest.mark.skipif(
    _BSLZ4_PY2_SKIP,
    reason="bslz4 tests not yet working on Python 2.7"
)
@pytest.mark.skipif(
    not os.path.exists(TESTDATA_LZ4),
    reason="run 'python3 tests/make_bs_testdata.py --zstd' first"
)
class TestMultiChunk:
    """Verify multi-chunk (loop-interchanged) output matches per-frame calls."""

    def test_sparse_multi_chunk(self):
        """Basic decompress: N chunks concatenated produces correct output."""
        h5py = pytest.importorskip("h5py")
        hdf5plugin = pytest.importorskip("hdf5plugin")

        with h5py.File(TESTDATA_LZ4, "r") as f:
            ds_keys = [k for k in f.keys() if "u16" in k.lower() or "uint16" in k.lower()]
            if not ds_keys:
                ds_keys = sorted(f.keys())
            ds_name = ds_keys[0]
            ds = f[ds_name]
            shape = ds.shape
            mask = np.ones(shape[1:], dtype=np.uint8)
            flat = mask.ravel()
            N = flat.size

            nchunks = min(3, shape[0])
            dtype = np.dtype(ds.dtype).type

            # Read multiple chunks (compressed sizes may vary)
            chunks = []
            offsets_list = []
            offset = 0
            for i in range(nchunks):
                _, chunk = ds.id.read_direct_chunk((i, 0, 0))
                buf = np.frombuffer(chunk, dtype=np.uint8)
                offsets_list.append(offset)
                offset += len(buf)
                chunks.append(buf)

            bigbuf = np.concatenate(chunks)
            offsets = np.array(offsets_list, dtype=np.int64)
            lengths = np.array([len(c) for c in chunks], dtype=np.int32)
            npx_pc  = np.zeros(nchunks, dtype=np.int32)

            out   = np.zeros(nchunks * N, dtype=dtype)
            outP  = np.zeros(nchunks * N, dtype=np.uint32)

            func = {
                np.dtype(np.uint8): _m.bslz4_u8,
                np.dtype(np.uint16): _m.bslz4_u16,
                np.dtype(np.uint32): _m.bslz4_u32,
            }[np.dtype(dtype)]

            total_npx = func(bigbuf, flat, out, outP, 0,
                             offsets, lengths, npx_pc)

            assert total_npx > 0
            for f_idx in range(nchunks):
                assert npx_pc[f_idx] > 0
                vals_f = out[f_idx * N : f_idx * N + npx_pc[f_idx]]
                # Verify values match single-chunk call
                s_offs = np.array([0], dtype=np.int64)
                s_lens = np.array([len(chunks[f_idx])], dtype=np.int32)
                s_npc  = np.zeros(1, dtype=np.int32)
                s_out  = np.zeros(N, dtype=dtype)
                s_outP = np.zeros(N, dtype=np.uint32)
                s_npx = func(chunks[f_idx], flat, s_out, s_outP, 0,
                             s_offs, s_lens, s_npc)
                assert s_npx == npx_pc[f_idx], \
                    "frame %d: npx %d vs single %d" % (f_idx, npx_pc[f_idx], s_npx)
                np.testing.assert_array_equal(vals_f, s_out[:s_npx],
                    err_msg="frame %d: values mismatch" % f_idx)
                np.testing.assert_array_equal(
                    outP[f_idx * N : f_idx * N + npx_pc[f_idx]],
                    s_outP[:s_npx],
                    err_msg="frame %d: indices mismatch" % f_idx)

    def test_csc_multi_chunk(self):
        """CSC: N chunks concatenated produces per-frame powder matching single calls."""
        h5py = pytest.importorskip("h5py")
        hdf5plugin = pytest.importorskip("hdf5plugin")

        with h5py.File(TESTDATA_LZ4, "r") as f:
            ds_keys = [k for k in f.keys() if "u16" in k.lower() or "uint16" in k.lower()]
            if not ds_keys:
                ds_keys = sorted(f.keys())
            ds_name = ds_keys[0]
            ds = f[ds_name]
            shape = ds.shape
            mask = np.ones(shape[1:], dtype=np.uint8)
            flat = mask.ravel()
            N = flat.size

            nchunks = min(3, shape[0])
            dtype = np.dtype(ds.dtype).type
            nout = 16

            # Read multiple chunks (compressed sizes may vary)
            chunks = []
            offsets_list = []
            offset = 0
            for i in range(nchunks):
                _, chunk = ds.id.read_direct_chunk((i, 0, 0))
                buf = np.frombuffer(chunk, dtype=np.uint8)
                offsets_list.append(offset)
                offset += len(buf)
                chunks.append(buf)

            bigbuf = np.concatenate(chunks)
            offsets = np.array(offsets_list, dtype=np.int64)
            lengths = np.array([len(c) for c in chunks], dtype=np.int32)
            npx_pc  = np.zeros(nchunks, dtype=np.int32)

            # CSC setup (simple identity-like matrix)
            csc_data = np.ones(N, dtype=np.float32)
            csc_indices = np.arange(N, dtype=np.uint32) % nout
            csc_indptr = np.arange(N + 1, dtype=np.uint32)

            func = {
                np.dtype(np.uint8): _m.bslz4_csc_u8,
                np.dtype(np.uint16): _m.bslz4_csc_u16,
                np.dtype(np.uint32): _m.bslz4_csc_u32,
            }[np.dtype(dtype)]

            powder = np.zeros(nchunks * nout, dtype=np.float64)
            outpx  = np.zeros(nchunks * N, dtype=dtype)
            outP   = np.zeros(nchunks * N, dtype=np.uint32)

            total_npx = func(bigbuf, flat, outpx, outP, 0,
                             powder, csc_data, csc_indices, csc_indptr,
                             offsets, lengths, npx_pc)

            assert total_npx > 0
            for f_idx in range(nchunks):
                assert npx_pc[f_idx] > 0

            powder_2d = powder.reshape((nchunks, nout))

            # Verify per-frame powder matches single-chunk calls
            for f_idx in range(nchunks):
                s_offs = np.array([0], dtype=np.int64)
                s_lens = np.array([len(chunks[f_idx])], dtype=np.int32)
                s_npc  = np.zeros(1, dtype=np.int32)
                s_powder = np.zeros(nout, dtype=np.float64)
                s_outpx  = np.zeros(N, dtype=dtype)
                s_outP   = np.zeros(N, dtype=np.uint32)
                s_npx = func(chunks[f_idx], flat, s_outpx, s_outP, 0,
                             s_powder, csc_data, csc_indices, csc_indptr,
                             s_offs, s_lens, s_npc)

                np.testing.assert_allclose(powder_2d[f_idx], s_powder,
                    rtol=1e-10,
                    err_msg="CSC powder mismatch frame %d" % f_idx)
                np.testing.assert_array_equal(
                    outpx[f_idx * N : f_idx * N + npx_pc[f_idx]],
                    s_outpx[:s_npx],
                    err_msg="CSC outpx mismatch frame %d" % f_idx)
                np.testing.assert_array_equal(
                    outP[f_idx * N : f_idx * N + npx_pc[f_idx]],
                    s_outP[:s_npx],
                    err_msg="CSC outP mismatch frame %d" % f_idx)
