"""Bit-perfect regression tests for bslz4/bszstd C functions.

Tests all enginexdtypexshapexdistribution combinations against
pure-numpy reference. Also compares against original bslz4_to_sparse
f2py output when available.

Test data is generated by make_bs_testdata.py if not present.
"""

import os
import numpy as np
import pytest
import c2ImageD11._cImageD11 as _m

TESTDATA_LZ4 = os.path.join(os.path.dirname(__file__), "bslz4_testdata.h5")
TESTDATA_ZSTD = os.path.join(os.path.dirname(__file__), "bszstd_testdata.h5")


# =============================================================================
# Helpers
# =============================================================================

def _ensure_testdata():
    """Generate test data if not present."""
    if not os.path.exists(TESTDATA_LZ4) or not os.path.exists(TESTDATA_ZSTD):
        script = os.path.join(os.path.dirname(__file__), "make_bs_testdata.py")
        if os.path.exists(script):
            os.system("python3 " + script + " --zstd")


def _pysparse(frame, mask, cut):
    """Pure-numpy reference: apply mask, threshold, return (values, indices)."""
    masked = frame * mask
    pixels = masked > cut
    if not pixels.any():
        return np.zeros(0, dtype=frame.dtype), np.zeros(0, dtype=np.uint32)
    return masked[pixels], np.where(pixels.ravel())[0].astype(np.uint32)


def _pysparse_csc(frame, mask, cut, data, indices, indptr, out):
    """Pure-numpy reference for CSC: sparse output + dot product."""
    vals, idxs = _pysparse(frame, mask, cut)
    out[:] = 0.0
    for j in range(len(frame.ravel())):
        v = frame.ravel()[j] * mask.ravel()[j]
        if v > 0:
            for k in range(indptr[j], indptr[j + 1]):
                out[indices[k]] += float(data[k]) * float(v)
    return vals, idxs


# =============================================================================
# Smoke tests
# =============================================================================

class TestBslz4Smoke:
    """Basic buffer protocol tests for all 12 Python-facing functions."""

    @pytest.mark.parametrize("func,dtype", [
        (_m.bslz4_u8,  np.uint8),
        (_m.bslz4_u16, np.uint16),
        (_m.bslz4_u32, np.uint32),
    ])
    def test_bslz4_basic(self, func, dtype):
        compressed = np.zeros(100, dtype=np.uint8)
        mask = np.ones(4, dtype=np.uint8)
        out = np.zeros(4, dtype=dtype)
        outP = np.zeros(4, dtype=np.uint32)
        npx = func(compressed, mask, out, outP, 0)
        assert isinstance(npx, int)

    @pytest.mark.parametrize("func,dtype", [
        (_m.bslz4_csc_u8,  np.uint8),
        (_m.bslz4_csc_u16, np.uint16),
        (_m.bslz4_csc_u32, np.uint32),
    ])
    def test_bslz4_csc(self, func, dtype):
        compressed = np.zeros(100, dtype=np.uint8)
        mask = np.ones(4, dtype=np.uint8)
        outpx = np.zeros(4, dtype=dtype)
        outP = np.zeros(4, dtype=np.uint32)
        out = np.zeros(8, dtype=np.float64)
        data = np.ones(4, dtype=np.float32)
        indices = np.zeros(4, dtype=np.uint32)
        indptr = np.arange(5, dtype=np.uint32)
        npx = func(compressed, mask, outpx, outP, 0, out, data, indices, indptr)
        assert isinstance(npx, int)

    @pytest.mark.parametrize("func,dtype", [
        (_m.bszstd_u8,  np.uint8),
        (_m.bszstd_u16, np.uint16),
        (_m.bszstd_u32, np.uint32),
    ])
    def test_bszstd_basic(self, func, dtype):
        compressed = np.zeros(100, dtype=np.uint8)
        mask = np.ones(4, dtype=np.uint8)
        out = np.zeros(4, dtype=dtype)
        outP = np.zeros(4, dtype=np.uint32)
        npx = func(compressed, mask, out, outP, 0)
        assert isinstance(npx, int)

    @pytest.mark.parametrize("func,dtype", [
        (_m.bszstd_csc_u8,  np.uint8),
        (_m.bszstd_csc_u16, np.uint16),
        (_m.bszstd_csc_u32, np.uint32),
    ])
    def test_bszstd_csc(self, func, dtype):
        compressed = np.zeros(100, dtype=np.uint8)
        mask = np.ones(4, dtype=np.uint8)
        outpx = np.zeros(4, dtype=dtype)
        outP = np.zeros(4, dtype=np.uint32)
        out = np.zeros(8, dtype=np.float64)
        data = np.ones(4, dtype=np.float32)
        indices = np.zeros(4, dtype=np.uint32)
        indptr = np.arange(5, dtype=np.uint32)
        npx = func(compressed, mask, outpx, outP, 0, out, data, indices, indptr)
        assert isinstance(npx, int)


# =============================================================================
# Bit-perfect regression (requires test data + h5py + hdf5plugin)
# =============================================================================

@pytest.mark.skipif(
    not os.path.exists(TESTDATA_LZ4),
    reason="run 'python3 tests/make_bs_testdata.py --zstd' first"
)
class TestBitPerfectLZ4:
    """Compare bslz4_* output against pure-numpy reference for LZ4 data."""

    ENGINES = {
        "lz4": {"basic": {np.uint8: _m.bslz4_u8, np.uint16: _m.bslz4_u16, np.uint32: _m.bslz4_u32},
                "csc":   {np.uint8: _m.bslz4_csc_u8, np.uint16: _m.bslz4_csc_u16, np.uint32: _m.bslz4_csc_u32}},
    }

    def _datasets(self):
        h5py = pytest.importorskip("h5py")
        hdf5plugin = pytest.importorskip("hdf5plugin")  # noqa
        with h5py.File(TESTDATA_LZ4, "r") as f:
            return [(name, f[name].shape, f[name].dtype) for name in sorted(f.keys())]

    def _test_dataset(self, ds_info, engine, cut=0):
        name, shape, dtype = ds_info
        dtype = np.dtype(dtype).type
        h5py = pytest.importorskip("h5py")
        mask = np.ones(shape[1:], dtype=np.uint8)
        nframes = min(shape[0], 4)

        func = self.ENGINES[engine]["basic"][dtype]
        N = mask.size
        vals = np.empty(N, dtype=dtype)
        inds = np.empty(N, dtype=np.uint32)

        with h5py.File(TESTDATA_LZ4, "r") as f:
            ds = f[name]
            for frame in range(nframes):
                ref_vals, ref_inds = _pysparse(ds[frame], mask, cut)
                chunk_info, chunk = ds.id.read_direct_chunk((frame, 0, 0))
                npx = func(chunk, mask.ravel(), vals, inds, cut)
                assert npx == len(ref_vals), \
                    f"npx mismatch: {npx} vs {len(ref_vals)} at frame={frame} cut={cut}"
                np.testing.assert_array_equal(vals[:npx], ref_vals,
                    err_msg=f"values mismatch at frame={frame} cut={cut}")
                np.testing.assert_array_equal(inds[:npx], ref_inds,
                    err_msg=f"indices mismatch at frame={frame} cut={cut}")

    def _test_dataset_csc(self, ds_info, engine, cut=0):
        name, shape, dtype = ds_info
        dtype = np.dtype(dtype).type
        h5py = pytest.importorskip("h5py")
        mask = np.ones(shape[1:], dtype=np.uint8)
        flat = mask.ravel()
        func = self.ENGINES[engine]["csc"][dtype]
        N = flat.size

        data = np.ones(N, dtype=np.float32)
        indices = np.zeros(N, dtype=np.uint32)
        indptr = np.arange(N + 1, dtype=np.uint32)
        outpx = np.empty(N, dtype=dtype)
        outP = np.empty(N, dtype=np.uint32)
        powder = np.zeros(1, dtype=np.float64)
        powder_ref = np.zeros(1, dtype=np.float64)

        with h5py.File(TESTDATA_LZ4, "r") as f:
            ds = f[name]
            for frame in range(min(shape[0], 2)):
                ref_vals, ref_inds = _pysparse_csc(ds[frame], mask, cut,
                                                   data, indices, indptr, powder_ref)
                chunk_info, chunk = ds.id.read_direct_chunk((frame, 0, 0))
                npx = func(chunk, flat, outpx, outP, cut,
                          powder, data, indices, indptr)
                assert npx == len(ref_vals), f"CSC npx mismatch frame={frame}"
                np.testing.assert_array_equal(outpx[:npx], ref_vals,
                    err_msg=f"CSC values mismatch frame={frame}")
                np.testing.assert_array_equal(outP[:npx], ref_inds,
                    err_msg=f"CSC indices mismatch frame={frame}")
                np.testing.assert_allclose(powder, powder_ref, rtol=1e-10,
                    err_msg=f"CSC powder mismatch frame={frame}")

    def test_lz4_basic_all_datasets(self):
        for ds_info in self._datasets():
            self._test_dataset(ds_info, "lz4", 0)
            self._test_dataset(ds_info, "lz4", 10)

    def test_lz4_csc_all_datasets(self):
        for ds_info in self._datasets():
            self._test_dataset_csc(ds_info, "lz4", 0)
            self._test_dataset_csc(ds_info, "lz4", 10)


@pytest.mark.skipif(
    not os.path.exists(TESTDATA_ZSTD),
    reason="run 'python3 tests/make_bs_testdata.py --zstd' first"
)
class TestBitPerfectZSTD:
    """Compare bszstd_* output against pure-numpy reference for ZSTD data."""

    FUNCS = {
        "basic": {np.uint8: _m.bszstd_u8, np.uint16: _m.bszstd_u16, np.uint32: _m.bszstd_u32},
        "csc":   {np.uint8: _m.bszstd_csc_u8, np.uint16: _m.bszstd_csc_u16, np.uint32: _m.bszstd_csc_u32},
    }

    def _datasets(self):
        h5py = pytest.importorskip("h5py")
        hdf5plugin = pytest.importorskip("hdf5plugin")  # noqa
        with h5py.File(TESTDATA_ZSTD, "r") as f:
            return [(name, f[name].shape, f[name].dtype) for name in sorted(f.keys())]

    def test_zstd_basic(self):
        for name, shape, dtype in self._datasets():
            dtype = np.dtype(dtype).type
            h5py = pytest.importorskip("h5py")
            mask = np.ones(shape[1:], dtype=np.uint8)
            func = self.FUNCS["basic"][dtype]
            N = mask.size
            vals = np.empty(N, dtype=dtype)
            inds = np.empty(N, dtype=np.uint32)

            with h5py.File(TESTDATA_ZSTD, "r") as f:
                ds = f[name]
                for frame in range(min(shape[0], 2)):
                    ref_vals, ref_inds = _pysparse(ds[frame], mask, 0)
                    chunk_info, chunk = ds.id.read_direct_chunk((frame, 0, 0))
                    chunk_buf = chunk
                    npx = func(chunk, mask.ravel(), vals, inds, 0)
                    assert npx == len(ref_vals)
                    np.testing.assert_array_equal(vals[:npx], ref_vals)
                    np.testing.assert_array_equal(inds[:npx], ref_inds)


# =============================================================================
# Equivalence vs original bslz4_to_sparse f2py
# =============================================================================

class TestF2pyEquivalence:
    """Compare c2ImageD11 output against original f2py extension."""

    def test_lz4_u16_c_layer(self):
        """Compare bslz4_u16 C function directly with the f2py version."""
        try:
            from bslz4_to_sparse import bslz4_uint16_t as f2py_fn
        except ImportError:
            pytest.skip("original bslz4_to_sparse not installed")

        h5py = pytest.importorskip("h5py")
        hdf5plugin = pytest.importorskip("hdf5plugin")  # noqa

        # Use the eiger data if available
        SRC = "/home/worker/test_data/eiger_lz4_u16.h5"
        if not os.path.exists(SRC):
            SRC = "/home/worker/test_data/eiger_0000.h5"
        if not os.path.exists(SRC):
            pytest.skip("no test data file found")

        with h5py.File(SRC, "r") as f:
            ds = f["/entry_0000/measurement/data"]
            mask = np.ones(ds.shape[1:], dtype=np.uint8)
            N = mask.size
            vals1 = np.empty(N, dtype=np.uint16)
            inds1 = np.empty(N, dtype=np.uint32)
            vals2 = np.empty(N, dtype=np.uint16)
            inds2 = np.empty(N, dtype=np.uint32)

            nframes = min(ds.shape[0], 10)
            for i in range(nframes):
                _, chunk = ds.id.read_direct_chunk((i, 0, 0))

                npx1 = f2py_fn(np.frombuffer(chunk, np.uint8), mask.ravel(), vals1, inds1, 0)
                npx2 = _m.bslz4_u16(chunk, mask.ravel(), vals2, inds2, 0)

                assert npx1 == npx2, f"frame {i}: npx mismatch"
                np.testing.assert_array_equal(vals1[:npx1], vals2[:npx2],
                    err_msg=f"frame {i}: values mismatch")
                np.testing.assert_array_equal(inds1[:npx1], inds2[:npx2],
                    err_msg=f"frame {i}: indices mismatch")

    def test_lz4_csc_u16_c_layer(self):
        """Compare bslz4_csc_u16 with original f2py version."""
        try:
            from bslz4_to_sparse import bslz4_csc_uint16_t as f2py_fn
        except ImportError:
            pytest.skip("original bslz4_to_sparse not installed")

        h5py = pytest.importorskip("h5py")
        hdf5plugin = pytest.importorskip("hdf5plugin")  # noqa

        SRC = "/home/worker/test_data/eiger_lz4_u16.h5"
        if not os.path.exists(SRC):
            SRC = "/home/worker/test_data/eiger_0000.h5"
        if not os.path.exists(SRC):
            pytest.skip("no test data file found")

        with h5py.File(SRC, "r") as f:
            ds = f["/entry_0000/measurement/data"]
            mask = np.ones(ds.shape[1:], dtype=np.uint8)
            flat = mask.ravel()
            N = flat.size

            data = np.ones(N, dtype=np.float32)
            indices = np.zeros(N, dtype=np.uint32)
            indptr = np.arange(N + 1, dtype=np.uint32)
            outpx1 = np.empty(N, dtype=np.uint16)
            outP1 = np.empty(N, dtype=np.uint32)
            powder1 = np.zeros(1, dtype=np.float64)
            outpx2 = np.empty(N, dtype=np.uint16)
            outP2 = np.empty(N, dtype=np.uint32)
            powder2 = np.zeros(1, dtype=np.float64)

            for i in range(min(ds.shape[0], 5)):
                _, chunk = ds.id.read_direct_chunk((i, 0, 0))

                npx1 = f2py_fn(np.frombuffer(chunk, np.uint8), flat, outpx1, outP1, 0,
                               powder1, data, indices, indptr)
                npx2 = _m.bslz4_csc_u16(chunk, flat, outpx2, outP2, 0,
                                        powder2, data, indices, indptr)

                assert npx1 == npx2, f"frame {i}: npx mismatch"
                np.testing.assert_array_equal(outpx1[:npx1], outpx2[:npx2])
                np.testing.assert_array_equal(outP1[:npx1], outP2[:npx2])
                np.testing.assert_allclose(powder1, powder2, rtol=1e-10)
