#!/usr/bin/env python
"""generate_bslz4.py - Generate C boilerplate and c2py23 interface definitions
for the bslz4/bszstd bitshuffle sparse decompression functions.

This script produces three output files from a single configuration table:

  src/bs_master.c        -- master compilation unit with template #includes
  src/bs_functions.h     -- forward declarations for all C functions
  _cImageD11_bslz4.c2py  -- c2py23 function definitions (setup.py splices
                            this into _cImageD11_base.c2py at build time)

Why a generator?
  The function count is combinatorial: 3 pixel types (u8/u16/u32)
  x 4 CSC data types (f32/u8/u16/u32) x 2 engines (LZ4/ZSTD)
  x 2 backends (KCB/bitshuffle-core) x 3 ISAs (SSE42/AVX2/AVX-512).
  That is 144 CSC functions plus 36 basic decompress functions.
  Writing these by hand is error-prone; the C preprocessor template
  expansion and the c2py23 type-check boilerplate follow exact
  mechanical patterns that a generator trivially handles.

Usage:
  python generate_bslz4.py          # writes all three files
  python generate_bslz4.py --check  # diff against current files (for CI)

Python 2.7 compatible (no f-strings, no type annotations).
"""

from __future__ import print_function
import os
import sys
import argparse

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ---------------------------------------------------------------------------
# Configuration tables
# ---------------------------------------------------------------------------

# Pixel types unpacked from compressed bitshuffle data
PIXEL_TYPES = [
    {"datatype": "uint8_t",  "dtshort": "u8",  "nb": 1,
     "py_format": "B", "c2py_format": "B"},
    {"datatype": "uint16_t", "dtshort": "u16", "nb": 2,
     "py_format": "H", "c2py_format": "H"},
    {"datatype": "uint32_t", "dtshort": "u32", "nb": 4,
     "py_format": "I", "c2py_format": "I"},
]

# CSC matrix data types: float (legacy) + integer (new exact-arithmetic)
# cscshort determines the suffix appended to function names.
# For float: suffix is empty (backward-compatible naming, e.g. bslz4_csc_u16_...)
# For integer: suffix like "cu16" -> function name bslz4_csc_u16_cu16_...
CSC_TYPES = [
    {"cscdatatype": "float",    "cscshort": "",
     "cformat": "f", "sumtype": "double",   "sformat": "d",
     "is_float": True},
]

ENGINES = [
    {"suffix": "",  "prefix": "bs",  "extra_flags": ""},
]

BACKENDS = [
    {"suffix": "kcb", "extra_flags": "-DUSE_KCB"},
]

ISAS = [
    {"suffix": "avx512", "isa_flag": "-mavx512f",
     "when_cond": "c2py_amd64_avx512f", "is_default": False},
    {"suffix": "avx2",   "isa_flag": "-mavx2",
     "when_cond": "c2py_amd64_avx2", "is_default": False},
    {"suffix": "sse42",  "isa_flag": "-msse4.2",
     "when_cond": None, "is_default": True},
]

# ---------------------------------------------------------------------------
# Naming helpers
# ---------------------------------------------------------------------------

def make_basic_fn_name(prefix, dtshort, backend, isa):
    """e.g. bslz4_u16_kcb_avx512"""
    return "{}_{}_{}_{}".format(prefix, dtshort, backend, isa)

def make_csc_fn_name(prefix, dtshort, cscshort, backend, isa):
    """e.g. bslz4_csc_u16_cu16_kcb_avx512 (int) or bslz4_csc_u16_kcb_avx512 (float)"""
    if cscshort:
        return "{}_csc_{}_{}_{}_{}".format(prefix, dtshort, cscshort, backend, isa)
    else:
        return "{}_csc_{}_{}_{}".format(prefix, dtshort, backend, isa)

def make_py_fn_name(prefix, dtshort, cscshort):
    """Python-visible function name. e.g. bslz4_csc_u16_cu16"""
    if cscshort:
        return "{}_csc_{}_{}".format(prefix, dtshort, cscshort)
    else:
        return "{}_csc_{}".format(prefix, dtshort)

def make_csc1d_fn_name(prefix, dtshort, cscshort, backend, isa):
    """e.g. bslz4_csc1d_u16_cu16_kcb_avx512 (int) or bslz4_csc1d_u16_kcb_avx512 (float)"""
    if cscshort:
        return "{}_csc1d_{}_{}_{}_{}".format(prefix, dtshort, cscshort, backend, isa)
    else:
        return "{}_csc1d_{}_{}_{}".format(prefix, dtshort, backend, isa)

def make_py_csc1d_fn_name(prefix, dtshort, cscshort):
    """Python-visible 1D CSC function name. e.g. bslz4_csc1d_u16_cu16"""
    if cscshort:
        return "{}_csc1d_{}_{}".format(prefix, dtshort, cscshort)
    else:
        return "{}_csc1d_{}".format(prefix, dtshort)

def make_kernel_suffix(backend, isa):
    """What gets passed via -DKERNEL_SUFFIX to cc"""
    return "_{}_{}".format(backend, isa)

def make_full_suffix(backend, isa):
    """Full suffix used in object file names"""
    return "_{}_{}".format(backend, isa)

# ---------------------------------------------------------------------------
# bs_master.c generator
# ---------------------------------------------------------------------------

BS_MASTER_HEADER = '''/* bs_master.c - bitshuffle sparse decompression master compilation unit.
 *
 * AUTO-GENERATED by generate_bslz4.py -- DO NOT EDIT BY HAND.
 *
 * Compiled multiple times with different -D flags:
 *   -DKERNEL_SUFFIX=_kcb_avx512  (or _kcb_sse42, etc.)
 *   -DUSE_KCB  (or leave undefined for bitshuffle-core)
 *
 * Each compilation includes bs_sparse_tmpl.c 3 times (once per pixel type),
 * bs_sparse_csc_tmpl.c 3 times (once per pixel type, f32 CSC), and
 * bs_sparse_csc_1d_tmpl.c 3 times (1D padded CSC).
 * Generates 3 basic + 3 CSC + 3 CSC1D = 9 functions per compilation unit.
 * Encoding (LZ4=2, ZSTD=3) is dispatched at runtime via parameter.
 */

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <limits.h>
#include <stdio.h>

/* --------------------------------------------------------------------------
 * Engine / Decompress dispatch
 * Encoding values (from bshuf_h5filter.h):
 *   2 = LZ4,   3 = ZSTD
 * -------------------------------------------------------------------------- */

#define FN_PREFIX bs
#include "vendor/lz4/lib/lz4.h"
#include "vendor/zstd/lib/zstd.h"

static inline int bs_decompress(const void *src, int srcSize,
                                void *dst, int dstSize, int encoding) {
    if (encoding == 3)
        return (int)ZSTD_decompress(dst, (size_t)dstSize, src, (size_t)srcSize);
    else
        return LZ4_decompress_safe((const char*)src, (char*)dst, srcSize, dstSize);
}

/* --------------------------------------------------------------------------
 * Bitshuffle backend selection
 * -------------------------------------------------------------------------- */

#ifdef USE_KCB
#include "vendor/kcb/src/bitshuffle.h"
#else
int64_t bshuf_untrans_bit_elem(const void* in, void* out, const size_t size,
        const size_t elem_size);
#endif

/* --------------------------------------------------------------------------
 * Utility macros
 * -------------------------------------------------------------------------- */

#define READ32BE(p) \\
  ((uint32_t)(255 & (p)[0]) << 24 |\\
   (uint32_t)(255 & (p)[1]) << 16 |\\
   (uint32_t)(255 & (p)[2]) <<  8 |\\
   (uint32_t)(255 & (p)[3]))

#define READ64BE(p) \\
  ((uint64_t)(255 & (p)[0]) << 56 |\\
   (uint64_t)(255 & (p)[1]) << 48 |\\
   (uint64_t)(255 & (p)[2]) << 40 |\\
   (uint64_t)(255 & (p)[3]) << 32 |\\
   (uint64_t)(255 & (p)[4]) << 24 |\\
   (uint64_t)(255 & (p)[5]) << 16 |\\
   (uint64_t)(255 & (p)[6]) <<  8 |\\
   (uint64_t)(255 & (p)[7]))

#ifndef unlikely
#ifdef _MSC_VER
#define unlikely
#else
#define unlikely(expr) (__builtin_expect(!!(expr), 0))
#endif
#endif

#define BLK 8192

#define CAT_I(a,b) a##b
#define CAT(a,b) CAT_I(a,b)
#define CAT3(a,b,c) CAT(CAT(a,b),c)
#define CAT4(a,b,c,d) CAT(CAT3(a,b,c),d)

#ifndef KERNEL_SUFFIX
#define KERNEL_SUFFIX _sse42
#endif

#define FULL_SUFFIX KERNEL_SUFFIX
'''

def generate_bs_master_c():
    """Generate the complete bs_master.c content."""
    lines = [BS_MASTER_HEADER]

    for px in PIXEL_TYPES:
        lines.append("")
        lines.append("/* ================================================================")
        lines.append(" * Pixel type: {} (NB={})".format(px["datatype"], px["nb"]))
        lines.append(" * ================================================================ */")
        lines.append("")
        lines.append("#define DATATYPE {}".format(px["datatype"]))
        lines.append("#define DT_SHORT {}".format(px["dtshort"]))
        lines.append("#define NB {}".format(px["nb"]))
        lines.append("")
        lines.append("#define KERNEL_FN CAT3(FN_PREFIX, _, CAT(DT_SHORT, FULL_SUFFIX))")
        lines.append('#include "bs_sparse_tmpl.c"')
        lines.append("")

        for csc in CSC_TYPES:
            cscshort = csc["cscshort"]
            if csc["is_float"]:
                lines.append("#define CSC_DATA_T {}".format(csc["cscdatatype"]))
                lines.append("#define CSC_SUM_T {}".format(csc["sumtype"]))
                lines.append("#define KERNEL_CSC_FN CAT3(FN_PREFIX, _csc_, CAT(DT_SHORT, FULL_SUFFIX))")
                lines.append('#include "bs_sparse_csc_tmpl.c"')
                lines.append("#define KERNEL_CSC1D_FN CAT3(FN_PREFIX, _csc1d_, CAT(DT_SHORT, FULL_SUFFIX))")
                lines.append('#include "bs_sparse_csc_1d_tmpl.c"')
            else:
                cscid = "CAT3(DT_SHORT, _, {})".format(cscshort)
                lines.append("#define CSC_DATA_T {}".format(csc["cscdatatype"]))
                lines.append("#define CSC_SUM_T {}".format(csc["sumtype"]))
                lines.append("#define KERNEL_CSC_FN CAT4(FN_PREFIX, _csc_, {}, FULL_SUFFIX)".format(cscid))
                lines.append('#include "bs_sparse_csc_tmpl.c"')
                lines.append("#define KERNEL_CSC1D_FN CAT4(FN_PREFIX, _csc1d_, {}, FULL_SUFFIX)".format(cscid))
                lines.append('#include "bs_sparse_csc_1d_tmpl.c"')

        lines.append("")
        lines.append("#undef DATATYPE")
        lines.append("#undef DT_SHORT")
        lines.append("#undef NB")
        lines.append("#undef KERNEL_FN")
        lines.append("#undef CSC_DATA_T")
        lines.append("#undef CSC_SUM_T")
        lines.append("#undef KERNEL_CSC_FN")
        lines.append("#undef KERNEL_CSC1D_FN")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# bs_functions.h generator
# ---------------------------------------------------------------------------

BS_FUNCTIONS_H_HEADER = '''/* Forward declarations for all bitshuffle sparse decompress functions.
 *
 * AUTO-GENERATED by generate_bslz4.py -- DO NOT EDIT BY HAND.
 *
 * {nfuncs} functions = {npixel} pixel types (u8/u16/u32)
 *                   x {nbasic} basic decompress
 *                   + {npixel} pixel types x {ncsc} CSC data types
 *                   x 1 engine (runtime dispatch via encoding param)
 *                   x {nbackends} backends (kcb/bs)
 *                   x {nisas} ISAs (sse42/avx2/avx512)
 *
 * encoding=2 for LZ4, encoding=3 for ZSTD.
 *
 * Used by c2py23 for wrapper codegen.
 */

#ifndef BS_FUNCTIONS_H
#define BS_FUNCTIONS_H

#include <stdint.h>
'''

def generate_bs_functions_h():
    """Generate the complete bs_functions.h content."""
    lines = []

    # Count totals for header comment
    npx = len(PIXEL_TYPES)
    ncsc = len(CSC_TYPES)
    neng = len(ENGINES)
    nbk = len(BACKENDS)
    nisa = len(ISAS)
    nbasic = npx * neng * nbk * nisa
    ncsc_total = npx * ncsc * neng * nbk * nisa
    nfuncs = nbasic + ncsc_total

    lines.append(BS_FUNCTIONS_H_HEADER.format(
        nfuncs=nfuncs, npixel=npx, nbasic="1", ncsc=ncsc,
        nengines=1, nbackends=nbk, nisas=nisa))

    for engine in ENGINES:
        prefix = engine["prefix"]
        eng_suffix = engine["suffix"]

        for backend in BACKENDS:
            bkd_suffix = backend["suffix"]

            lines.append("")
            lines.append("/* ======================================================="
                         "======================")
            lines.append(" * {} engine x {} backend".format(
                eng_suffix.upper(), bkd_suffix.upper()))
            lines.append(" * ======================================================="
                         "======================")

            for isa in ISAS:
                isa_suffix = isa["suffix"]
                for px in PIXEL_TYPES:
                    dtshort = px["dtshort"]
                    datatype = px["datatype"]
                    fn_basic = make_basic_fn_name(prefix, dtshort,
                                                  bkd_suffix, isa_suffix)

                    lines.append("")
                    lines.append("/* {} basic */".format(dtshort))
                    lines.append(
                        "int {fn}(const uint8_t *restrict compressed, "
                        "int compressed_length, "
                        "const uint8_t *restrict mask, int NIJ, "
                        "{dt} *restrict output, uint32_t *restrict output_adr, "
                        "int threshold, int encoding, "
                        "const int64_t *restrict chunk_offsets, "
                        "const int32_t *restrict chunk_lengths, "
                        "int nchunks, "
                        "int32_t *restrict npx_per_chunk);".format(fn=fn_basic, dt=datatype)
                    )

                    for csc in CSC_TYPES:
                        cscshort = csc["cscshort"]
                        cscdatatype = csc["cscdatatype"]
                        sumtype = csc["sumtype"]
                        fn_csc = make_csc_fn_name(prefix, dtshort, cscshort,
                                                  bkd_suffix, isa_suffix)
                        csc_label = cscshort if cscshort else "f32"

                        lines.append("")
                        lines.append("/* {} CSC {} */".format(dtshort, csc_label))
                        lines.append(
                            "int {fn}(const uint8_t *restrict compressed, "
                            "int compressed_length, "
                            "const uint8_t *restrict mask, int NIJ, "
                            "{dt} *restrict outpx, uint32_t *restrict output_adr, "
                            "int threshold, int encoding, "
                             "{sum} *restrict output, int nout_total, "
                             "{cscdt} *restrict data, uint32_t *restrict indices, "
                             "uint32_t *restrict indptr, "
                            "const int64_t *restrict chunk_offsets, "
                            "const int32_t *restrict chunk_lengths, "
                            "int nchunks, "
                            "int32_t *restrict npx_per_chunk);".format(
                                fn=fn_csc, dt=datatype, sum=sumtype,
                                cscdt=cscdatatype)
                        )

                        fn_csc1d = make_csc1d_fn_name(prefix, dtshort, cscshort,
                                                      bkd_suffix, isa_suffix)
                        lines.append("")
                        lines.append("/* {} CSC1D {} */".format(dtshort, csc_label))
                        lines.append(
                            "int {fn}(const uint8_t *restrict compressed, "
                            "int compressed_length, "
                            "const uint8_t *restrict mask, int NIJ, "
                            "{dt} *restrict outpx, uint32_t *restrict output_adr, "
                            "int threshold, int encoding, "
                             "{sum} *restrict output, int nout_total, "
                             "const {cscdt} *restrict csc_flat, "
                            "const uint32_t *restrict csc_first_bin, "
                            "int csc_entries_per_pixel, "
                            "const int64_t *restrict chunk_offsets, "
                            "const int32_t *restrict chunk_lengths, "
                            "int nchunks, "
                            "int32_t *restrict npx_per_chunk);".format(
                                fn=fn_csc1d, dt=datatype, sum=sumtype,
                                cscdt=cscdatatype)
                        )

    lines.append("")
    lines.append("#endif /* BS_FUNCTIONS_H */")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# c2py23 .c2py fragment generator
# ---------------------------------------------------------------------------

C2PY_HEADER = '''  # ===================================================================
  # bs_master.c -- bitshuffle sparse decompress
  #
  # AUTO-GENERATED by generate_bslz4.py -- DO NOT EDIT BY HAND.
  #
  # {nbasic} basic sparse decompress Python functions
  # {ncsc} CSC (powder integration) Python functions
  # 3 pixel types (u8/u16/u32) x 2 function types (basic/CSC/CSC1D).
  # Each with {nvariant} c2py23 variants ({nbackends} backends x {nisas} ISAs).
  # encoding=2 for LZ4, encoding=3 for ZSTD.
  # ===================================================================
'''

def _py_sig_entry_basic(prefix, dtshort, py_format):
    """Generate a c2py23 basic decompress function entry."""
    DT_LABEL = {"u8": "uint8", "u16": "uint16", "u32": "uint32"}
    fn_name = "{}_{}".format(prefix, dtshort)
    lines = []
    lines.append("")
    lines.append('  - py_sig: "{}'.format(fn_name) +
                 '(compressed: buffer, mask: buffer, '
                 'out: buffer, outP: buffer, thresh: int, '
                 'encoding: int, '
                 'chunk_offsets: buffer, chunk_lengths: buffer, '
                 'npx_per_chunk: buffer) -> int"')
    dt_label = DT_LABEL.get(dtshort, dtshort)
    lines.append('    doc: "Bitshuffle decompress + unshuffle to sparse '
                 '({} pixels, encoding=2 LZ4, 3 ZSTD). Returns total npx."'.format(dtshort))
    lines.append('    params:')
    lines.append('      compressed: "Concatenated bitshuffle-LZ4/ZSTD compressed bytes (uint8)."')
    lines.append('      mask: "Detector mask (uint8, 1=active). mask[pixel]=1 for active pixels, 0=masked."')
    lines.append('      out: "Output pixel values ({0}). Per-chunk contiguous layout: chunk c writes to out[c*NIJ : (c+1)*NIJ]."'.format(dt_label))
    lines.append('      outP: "Output flat pixel indices (uint32). Same per-chunk layout as out."')
    lines.append('      thresh: "Pixel intensity threshold. Only pixels with mask[pixel] * value > thresh are kept."')
    lines.append('      encoding: "Compression format: 2=LZ4, 3=ZSTD."')
    lines.append('      chunk_offsets: "Byte offsets into compressed buffer (int64, one per chunk). Pass [0] for single-chunk."')
    lines.append('      chunk_lengths: "Compressed byte length of each chunk (int32, one per chunk)."')
    lines.append('      npx_per_chunk: "Per-chunk npx output (int32, one per chunk). Written by the function."')
    lines.append('    checks:')
    lines.append('      - "compressed.format == \'B\'"')
    lines.append('      - "mask.format == \'B\'"')
    lines.append('      - "out.format == \'{}\'"'.format(py_format))
    lines.append('      - "outP.format == \'I\'"')
    lines.append('      - "chunk_offsets.format == \'q\' or chunk_offsets.format == \'l\'"')
    lines.append('      - "chunk_lengths.format == \'i\'"')
    lines.append('      - "npx_per_chunk.format == \'i\'"')
    lines.append('      - "chunk_offsets.n == chunk_lengths.n"')
    lines.append('      - "chunk_offsets.n == npx_per_chunk.n"')
    lines.append('    gil_release: true')
    lines.append('    c_overloads:')
    when = ('      - when: "compressed.format == \'B\' and '
            'mask.format == \'B\' and out.format == \'{pf}\' '
            'and outP.format == \'I\' '
            'and (chunk_offsets.format == \'q\' or chunk_offsets.format == \'l\') '
            'and chunk_lengths.format == \'i\' '
            'and npx_per_chunk.format == \'i\'"'.format(pf=py_format))
    lines.append(when)
    lines.append('        map: {compressed: "compressed.ptr", '
                 'compressed_length: "compressed.shape[0]", '
                 'mask: "mask.ptr", NIJ: "mask.shape[0]", '
                 'output: "out.ptr", output_adr: "outP.ptr", '
                 'threshold: thresh, encoding: encoding, '
                 'chunk_offsets: "chunk_offsets.ptr", '
                 'chunk_lengths: "chunk_lengths.ptr", '
                 'nchunks: "chunk_offsets.shape[0]", '
                 'npx_per_chunk: "npx_per_chunk.ptr"}')
    lines.append('        group: {}'.format(fn_name))

    return lines


def _py_sig_variants_basic(prefix, dtshort):
    """Generate the variants block for a basic decompress function."""
    ISA_DOC = {"avx512": "AVX-512 fast path.", "avx2": "AVX2 fast path.", "sse42": "SSE4.2 fallback."}
    px = [p for p in PIXEL_TYPES if p["dtshort"] == dtshort][0]
    datatype = px["datatype"]

    lines = []
    lines.append('        variants:')
    for bk in BACKENDS:
        bkd = bk["suffix"]
        for isa in ISAS:
            isa_s = isa["suffix"]
            fn_name = make_basic_fn_name(prefix, dtshort, bkd, isa_s)
            name = "{}_{}".format(bkd, isa_s)
            sig = ("int {fn}(const uint8_t *compressed, int compressed_length, "
                   "const uint8_t *mask, int NIJ, "
                   "{dt} *output, uint32_t *output_adr, "
                   "int threshold, int encoding, "
                   "const int64_t *chunk_offsets, "
                   "const int32_t *chunk_lengths, "
                   "int nchunks, "
                   "int32_t *npx_per_chunk) -> int".format(fn=fn_name, dt=datatype))
            lines.append('          - name: "{}"'.format(name))
            lines.append('            sig: "{}"'.format(sig))
            if isa["when_cond"]:
                lines.append('            when: "{}"'.format(isa["when_cond"]))
            lines.append('            doc: "{}"'.format(ISA_DOC.get(isa_s, "")))
    return lines


def _py_sig_entry_csc(prefix, dtshort, csc, py_format):
    """Generate a c2py23 CSC function entry."""
    DT_LABEL = {"u8": "uint8", "u16": "uint16", "u32": "uint32"}
    cscshort = csc["cscshort"]
    cformat = csc["cformat"]
    sformat = csc["sformat"]
    fn_name = make_py_fn_name(prefix, dtshort, cscshort)

    if csc["is_float"]:
        type_desc = "float"
    elif cformat == "B":
        type_desc = "uint8"
    elif cformat == "H":
        type_desc = "uint16"
    else:
        type_desc = "uint32"

    if prefix == "bslz4":
        eng_label = "LZ4"
    else:
        eng_label = "ZSTD"

    dt_label = DT_LABEL.get(dtshort, dtshort)

    lines = []
    lines.append("")
    lines.append('  - py_sig: "{}'.format(fn_name) +
                 '(compressed: buffer, mask: buffer, '
                 'outpx: buffer, outP: buffer, thresh: int, '
                 'encoding: int, '
                 'out: buffer, data: buffer, '
                 'indices: buffer, indptr: buffer, '
                 'chunk_offsets: buffer, chunk_lengths: buffer, '
                 'npx_per_chunk: buffer) -> int"')
    lines.append('    doc: "Bitshuffle decompress + CSC accumulate '
                 '({} CSC data, {} pixels, encoding=2 LZ4, 3 ZSTD). '
                 'Returns total npx."'.format(type_desc, dtshort))
    lines.append('    params:')
    lines.append('      compressed: "Concatenated bitshuffle-LZ4/ZSTD compressed bytes (uint8)."')
    lines.append('      mask: "Detector mask (uint8, 1=active). mask[pixel]=1 for active, 0=masked."')
    lines.append('      outpx: "Output pixel values above threshold ({0}). Per-chunk layout: chunk c writes to outpx[c*NIJ : (c+1)*NIJ]."'.format(dt_label))
    lines.append('      outP: "Output flat pixel indices (uint32). Same per-chunk layout as outpx."')
    lines.append('      thresh: "Pixel intensity threshold. Only pixels with mask[pixel] * value > thresh are kept."')
    lines.append('      encoding: "Compression format: 2=LZ4, 3=ZSTD."')
    lines.append('      out: "Powder histogram output (float64). Chunk c writes to out[c*NOUT : (c+1)*NOUT] where NOUT = nbins."')
    lines.append('      data: "CSC matrix data values (float32)."')
    lines.append('      indices: "CSC row indices (uint32)."')
    lines.append('      indptr: "CSC column pointers (uint32, size NIJ+1). indptr[p]..indptr[p+1] spans pixel p entries."')
    lines.append('      chunk_offsets: "Byte offsets into compressed buffer (int64, one per chunk)."')
    lines.append('      chunk_lengths: "Compressed byte length of each chunk (int32)."')
    lines.append('      npx_per_chunk: "Per-chunk npx output (int32, one per chunk). Written by the function."')
    lines.append('    checks:')
    lines.append('      - "compressed.format == \'B\'"')
    lines.append('      - "mask.format == \'B\'"')
    lines.append('      - "outpx.format == \'{}\'"'.format(py_format))
    lines.append('      - "outP.format == \'I\'"')
    if csc["is_float"]:
        lines.append('      - "out.format == \'d\'"')
        lines.append('      - "data.format == \'f\'"')
        out_check = 'out.format == \'d\''
        data_check = 'data.format == \'f\''
    else:
        # uint64 may report as 'L' or 'Q' depending on platform
        lines.append('      - "out.format == \'Q\' or out.format == \'L\'"')
        lines.append('      - "data.format == \'{}\'"'.format(cformat))
        out_check = "out.format == 'Q' or out.format == 'L'"
        data_check = "data.format == '{}'".format(cformat)
    lines.append('      - "indices.format == \'I\'"')
    lines.append('      - "indptr.format == \'I\'"')
    lines.append('      - "chunk_offsets.format == \'q\' or chunk_offsets.format == \'l\'"')
    lines.append('      - "chunk_lengths.format == \'i\'"')
    lines.append('      - "npx_per_chunk.format == \'i\'"')
    lines.append('      - "chunk_offsets.n == chunk_lengths.n"')
    lines.append('      - "chunk_offsets.n == npx_per_chunk.n"')
    lines.append('      - "out.shape[0] % chunk_offsets.shape[0] == 0"')
    lines.append('    gil_release: true')
    lines.append('    c_overloads:')
    lines.append('')
    when = ('      - when: "compressed.format == \'B\' and '
            'mask.format == \'B\' and outpx.format == \'{pf}\' '
            'and outP.format == \'I\' '
            'and {oc} and {dc} '
            'and indices.format == \'I\' and indptr.format == \'I\' '
            'and (chunk_offsets.format == \'q\' or chunk_offsets.format == \'l\') '
            'and chunk_lengths.format == \'i\' '
            'and npx_per_chunk.format == \'i\'"'.format(
                pf=py_format, oc=out_check, dc=data_check))
    lines.append(when)
    lines.append('        map: {compressed: "compressed.ptr", '
                 'compressed_length: "compressed.shape[0]", '
                 'mask: "mask.ptr", NIJ: "mask.shape[0]", '
                 'outpx: "outpx.ptr", output_adr: "outP.ptr", '
                 'threshold: thresh, encoding: encoding, '
                 'output: "out.ptr", nout_total: "out.shape[0]", '
                 'data: "data.ptr", indices: "indices.ptr", '
                'indptr: "indptr.ptr", '
                 'chunk_offsets: "chunk_offsets.ptr", '
                 'chunk_lengths: "chunk_lengths.ptr", '
                 'nchunks: "chunk_offsets.shape[0]", '
                 'npx_per_chunk: "npx_per_chunk.ptr"}')
    lines.append('        group: {}'.format(fn_name))

    return lines


def _py_sig_variants_csc(prefix, dtshort, csc):
    """Generate the variants block for a CSC function."""
    ISA_DOC = {"avx512": "AVX-512 fast path.", "avx2": "AVX2 fast path.", "sse42": "SSE4.2 fallback."}
    cscshort = csc["cscshort"]
    cscdatatype = csc["cscdatatype"]
    sumtype = csc["sumtype"]

    px = [p for p in PIXEL_TYPES if p["dtshort"] == dtshort][0]
    datatype = px["datatype"]

    lines = []
    lines.append('        variants:')
    for bk in BACKENDS:
        bkd = bk["suffix"]
        for isa in ISAS:
            isa_s = isa["suffix"]
            fn_name = make_csc_fn_name(prefix, dtshort, cscshort, bkd, isa_s)
            name = "{}_{}".format(bkd, isa_s)
            sig = ("int {fn}(const uint8_t *compressed, int compressed_length, "
                   "const uint8_t *mask, int NIJ, "
                   "{dt} *outpx, uint32_t *output_adr, int threshold, "
                   "int encoding, "
                   "{sum} *output, int nout_total, "
                   "{cscdt} *data, uint32_t *indices, "
                   "uint32_t *indptr, "
                   "const int64_t *chunk_offsets, "
                   "const int32_t *chunk_lengths, "
                   "int nchunks, "
                   "int32_t *npx_per_chunk) -> int".format(
                       fn=fn_name, dt=datatype, sum=sumtype, cscdt=cscdatatype))
            lines.append('          - name: "{}"'.format(name))
            lines.append('            sig: "{}"'.format(sig))
            if isa["when_cond"]:
                lines.append('            when: "{}"'.format(isa["when_cond"]))
            lines.append('            doc: "{}"'.format(ISA_DOC.get(isa_s, "")))
    return lines


def _py_sig_entry_csc1d(prefix, dtshort, csc, py_format):
    """Generate a c2py23 CSC1D function entry."""
    DT_LABEL = {"u8": "uint8", "u16": "uint16", "u32": "uint32"}
    cscshort = csc["cscshort"]
    cformat = csc["cformat"]
    sformat = csc["sformat"]
    fn_name = make_py_csc1d_fn_name(prefix, dtshort, cscshort)

    if csc["is_float"]:
        type_desc = "float"
    elif cformat == "B":
        type_desc = "uint8"
    elif cformat == "H":
        type_desc = "uint16"
    else:
        type_desc = "uint32"

    if prefix == "bslz4":
        eng_label = "LZ4"
    else:
        eng_label = "ZSTD"

    dt_label = DT_LABEL.get(dtshort, dtshort)

    lines = []
    lines.append("")
    lines.append('  - py_sig: "{}'.format(fn_name) +
                 '(compressed: buffer, mask: buffer, '
                 'outpx: buffer, outP: buffer, thresh: int, '
                 'encoding: int, '
                 'out: buffer, csc_flat: buffer, csc_first_bin: buffer, '
                 'csc_entries_per_pixel: int, '
                 'chunk_offsets: buffer, chunk_lengths: buffer, '
                 'npx_per_chunk: buffer) -> int"')
    lines.append('    doc: "Bitshuffle 1D padded CSC decompress '
                 '({} CSC data, {} pixels, encoding=2 LZ4, 3 ZSTD). '
                 'Returns total npx."'.format(type_desc, dtshort))
    lines.append('    params:')
    lines.append('      compressed: "Concatenated bitshuffle-LZ4/ZSTD compressed bytes (uint8)."')
    lines.append('      mask: "Detector mask (uint8, 1=active). mask[pixel]=1 for active, 0=masked."')
    lines.append('      outpx: "Output pixel values above threshold ({0}). Per-chunk layout."'.format(dt_label))
    lines.append('      outP: "Output flat pixel indices (uint32). Per-chunk layout."')
    lines.append('      thresh: "Pixel intensity threshold."')
    lines.append('      encoding: "Compression format: 2=LZ4, 3=ZSTD."')
    lines.append('      out: "Powder histogram output (float64). Per-chunk layout."')
    lines.append('      csc_flat: "Flattened 1D-padded CSC weights (float32, shape NIJ * entries_per_pixel)."')
    lines.append('      csc_first_bin: "First histogram bin index per pixel (uint32, shape NIJ)."')
    lines.append('      csc_entries_per_pixel: "Number of CSC entries per pixel (pad width)."')
    lines.append('      chunk_offsets: "Byte offsets into compressed buffer (int64, one per chunk)."')
    lines.append('      chunk_lengths: "Compressed byte length of each chunk (int32)."')
    lines.append('      npx_per_chunk: "Per-chunk npx output (int32, one per chunk)."')
    lines.append('    checks:')
    lines.append('      - "compressed.format == \'B\'"')
    lines.append('      - "mask.format == \'B\'"')
    lines.append('      - "outpx.format == \'{}\'"'.format(py_format))
    lines.append('      - "outP.format == \'I\'"')
    if csc["is_float"]:
        lines.append('      - "out.format == \'d\'"')
        out_check = 'out.format == \'d\''
    else:
        lines.append('      - "out.format == \'Q\' or out.format == \'L\'"')
        out_check = "out.format == 'Q' or out.format == 'L'"
    lines.append('      - "csc_flat.format == \'{}\'"'.format(cformat))
    lines.append('      - "csc_first_bin.format == \'I\'"')
    lines.append('      - "chunk_offsets.format == \'q\' or chunk_offsets.format == \'l\'"')
    lines.append('      - "chunk_lengths.format == \'i\'"')
    lines.append('      - "npx_per_chunk.format == \'i\'"')
    lines.append('      - "chunk_offsets.n == chunk_lengths.n"')
    lines.append('      - "chunk_offsets.n == npx_per_chunk.n"')
    lines.append('      - "out.shape[0] % chunk_offsets.shape[0] == 0"')
    lines.append('    gil_release: true')
    lines.append('    c_overloads:')

    when = ('      - when: "compressed.format == \'B\' and '
            'mask.format == \'B\' and outpx.format == \'{pf}\' '
            'and outP.format == \'I\' '
            'and {oc} '
            'and csc_flat.format == \'{cf}\' '
            'and csc_first_bin.format == \'I\' '
            'and (chunk_offsets.format == \'q\' or chunk_offsets.format == \'l\') '
            'and chunk_lengths.format == \'i\' '
            'and npx_per_chunk.format == \'i\'"'.format(
                pf=py_format, oc=out_check, cf=cformat))
    lines.append(when)
    lines.append('        map: {compressed: "compressed.ptr", '
                 'compressed_length: "compressed.shape[0]", '
                 'mask: "mask.ptr", NIJ: "mask.shape[0]", '
                 'outpx: "outpx.ptr", output_adr: "outP.ptr", '
                 'threshold: thresh, encoding: encoding, '
                 'output: "out.ptr", '
                 'nout_total: "out.shape[0]", '
                 'csc_flat: "csc_flat.ptr", '
                 'csc_first_bin: "csc_first_bin.ptr", '
                 'csc_entries_per_pixel: csc_entries_per_pixel, '
                 'chunk_offsets: "chunk_offsets.ptr", '
                 'chunk_lengths: "chunk_lengths.ptr", '
                 'nchunks: "chunk_offsets.shape[0]", '
                 'npx_per_chunk: "npx_per_chunk.ptr"}')
    lines.append('        group: {}'.format(fn_name))

    return lines


def _py_sig_variants_csc1d(prefix, dtshort, csc):
    """Generate the variants block for a CSC1D function."""
    ISA_DOC = {"avx512": "AVX-512 fast path.", "avx2": "AVX2 fast path.", "sse42": "SSE4.2 fallback."}
    cscshort = csc["cscshort"]
    cscdatatype = csc["cscdatatype"]
    sumtype = csc["sumtype"]

    px = [p for p in PIXEL_TYPES if p["dtshort"] == dtshort][0]
    datatype = px["datatype"]

    lines = []
    lines.append('        variants:')
    for bk in BACKENDS:
        bkd = bk["suffix"]
        for isa in ISAS:
            isa_s = isa["suffix"]
            fn_name = make_csc1d_fn_name(prefix, dtshort, cscshort, bkd, isa_s)
            name = "{}_{}".format(bkd, isa_s)
            sig = ("int {fn}(const uint8_t *compressed, int compressed_length, "
                   "const uint8_t *mask, int NIJ, "
                   "{dt} *outpx, uint32_t *output_adr, int threshold, "
                   "int encoding, "
                   "{sum} *output, int nout_total, "
                   "const {cscdt} *csc_flat, "
                   "const uint32_t *csc_first_bin, "
                   "int csc_entries_per_pixel, "
                   "const int64_t *chunk_offsets, "
                   "const int32_t *chunk_lengths, "
                   "int nchunks, "
                   "int32_t *npx_per_chunk) -> int".format(
                       fn=fn_name, dt=datatype, sum=sumtype, cscdt=cscdatatype))
            lines.append('          - name: "{}"'.format(name))
            lines.append('            sig: "{}"'.format(sig))
            if isa["when_cond"]:
                lines.append('            when: "{}"'.format(isa["when_cond"]))
            lines.append('            doc: "{}"'.format(ISA_DOC.get(isa_s, "")))
    return lines


def generate_c2py():
    """Generate the bslz4 section of the .c2py file."""
    lines = []

    nbasic = len(PIXEL_TYPES) * len(ENGINES)
    ncsc = len(PIXEL_TYPES) * len(CSC_TYPES) * len(ENGINES)
    nvariant = len(BACKENDS) * len(ISAS)

    lines.append(C2PY_HEADER.format(
        nbasic=nbasic, ncsc=ncsc, nvariant=nvariant,
        nbackends=len(BACKENDS), nisas=len(ISAS)))

    for engine in ENGINES:
        prefix = engine["prefix"]
        for px in PIXEL_TYPES:
            dtshort = px["dtshort"]
            py_format = px["py_format"]

            # Basic decompress function
            entry_lines = _py_sig_entry_basic(prefix, dtshort, py_format)
            lines.extend(entry_lines)
            variant_lines = _py_sig_variants_basic(prefix, dtshort)
            lines.extend(variant_lines)

    for engine in ENGINES:
        prefix = engine["prefix"]
        for px in PIXEL_TYPES:
            dtshort = px["dtshort"]
            py_format = px["py_format"]
            for csc in CSC_TYPES:
                # CSC function
                entry_lines = _py_sig_entry_csc(prefix, dtshort, csc,
                                                 py_format)
                lines.extend(entry_lines)
                variant_lines = _py_sig_variants_csc(prefix, dtshort, csc)
                lines.extend(variant_lines)

                # CSC1D function
                entry_lines = _py_sig_entry_csc1d(prefix, dtshort, csc,
                                                   py_format)
                lines.extend(entry_lines)
                variant_lines = _py_sig_variants_csc1d(prefix, dtshort, csc)
                lines.extend(variant_lines)

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

OUTPUTS = {
    "src/bslz4/bs_master.c": generate_bs_master_c,
    "src/bslz4/bs_functions.h": generate_bs_functions_h,
    "interface/_cImageD11_bslz4.c2py": generate_c2py,
}


def main():
    parser = argparse.ArgumentParser(
        description="Generate bslz4 C boilerplate and c2py23 definitions")
    parser.add_argument("--check", action="store_true",
                        help="Check generated output matches existing files")
    args = parser.parse_args()

    for relpath, generator in sorted(OUTPUTS.items()):
        outpath = os.path.join(REPO, relpath)
        content = generator()

        if args.check:
            if not os.path.exists(outpath):
                print("MISSING: {}".format(relpath))
                sys.exit(1)
            with open(outpath, "r") as f:
                existing = f.read()
            if existing != content:
                print("MISMATCH: {} (re-run generate_bslz4.py)".format(relpath))
                sys.exit(1)
            print("OK: {}".format(relpath))
        else:
            with open(outpath, "w") as f:
                f.write(content)
            print("WROTE: {} ({:,d} bytes)".format(relpath, len(content)))


if __name__ == "__main__":
    main()
