/* Forward declarations for all bitshuffle sparse decompress functions.
 *
 * AUTO-GENERATED by generate_bslz4.py -- DO NOT EDIT BY HAND.
 *
 * 36 functions = 3 pixel types (u8/u16/u32)
 *                   x 1 basic decompress
 *                   + 3 pixel types x 1 CSC data types
 *                     (f32/u8/u16/u32)
 *                   x 2 engines (lz4/zstd)
 *                   x 1 backends (kcb/bs)
 *                   x 3 ISAs (sse42/avx2/avx512)
 *
 * Used by c2py23 for wrapper codegen.
 */

#ifndef BS_FUNCTIONS_H
#define BS_FUNCTIONS_H

#include <stdint.h>


/* =============================================================================
 * LZ4 engine x KCB backend
 * =============================================================================

/* u8 basic */
int bslz4_u8_kcb_avx512(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint8_t *restrict output, uint32_t *restrict output_adr, int threshold, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u8 CSC f32 */
int bslz4_csc_u8_kcb_avx512(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint8_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, float *restrict data, uint32_t *restrict indices, uint32_t *restrict indptr, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u8 CSC1D f32 */
int bslz4_csc1d_u8_kcb_avx512(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint8_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, const float *restrict csc_flat, const uint32_t *restrict csc_first_bin, int csc_entries_per_pixel, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u16 basic */
int bslz4_u16_kcb_avx512(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint16_t *restrict output, uint32_t *restrict output_adr, int threshold, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u16 CSC f32 */
int bslz4_csc_u16_kcb_avx512(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint16_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, float *restrict data, uint32_t *restrict indices, uint32_t *restrict indptr, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u16 CSC1D f32 */
int bslz4_csc1d_u16_kcb_avx512(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint16_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, const float *restrict csc_flat, const uint32_t *restrict csc_first_bin, int csc_entries_per_pixel, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u32 basic */
int bslz4_u32_kcb_avx512(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint32_t *restrict output, uint32_t *restrict output_adr, int threshold, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u32 CSC f32 */
int bslz4_csc_u32_kcb_avx512(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint32_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, float *restrict data, uint32_t *restrict indices, uint32_t *restrict indptr, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u32 CSC1D f32 */
int bslz4_csc1d_u32_kcb_avx512(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint32_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, const float *restrict csc_flat, const uint32_t *restrict csc_first_bin, int csc_entries_per_pixel, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u8 basic */
int bslz4_u8_kcb_avx2(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint8_t *restrict output, uint32_t *restrict output_adr, int threshold, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u8 CSC f32 */
int bslz4_csc_u8_kcb_avx2(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint8_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, float *restrict data, uint32_t *restrict indices, uint32_t *restrict indptr, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u8 CSC1D f32 */
int bslz4_csc1d_u8_kcb_avx2(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint8_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, const float *restrict csc_flat, const uint32_t *restrict csc_first_bin, int csc_entries_per_pixel, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u16 basic */
int bslz4_u16_kcb_avx2(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint16_t *restrict output, uint32_t *restrict output_adr, int threshold, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u16 CSC f32 */
int bslz4_csc_u16_kcb_avx2(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint16_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, float *restrict data, uint32_t *restrict indices, uint32_t *restrict indptr, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u16 CSC1D f32 */
int bslz4_csc1d_u16_kcb_avx2(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint16_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, const float *restrict csc_flat, const uint32_t *restrict csc_first_bin, int csc_entries_per_pixel, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u32 basic */
int bslz4_u32_kcb_avx2(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint32_t *restrict output, uint32_t *restrict output_adr, int threshold, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u32 CSC f32 */
int bslz4_csc_u32_kcb_avx2(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint32_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, float *restrict data, uint32_t *restrict indices, uint32_t *restrict indptr, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u32 CSC1D f32 */
int bslz4_csc1d_u32_kcb_avx2(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint32_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, const float *restrict csc_flat, const uint32_t *restrict csc_first_bin, int csc_entries_per_pixel, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u8 basic */
int bslz4_u8_kcb_sse42(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint8_t *restrict output, uint32_t *restrict output_adr, int threshold, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u8 CSC f32 */
int bslz4_csc_u8_kcb_sse42(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint8_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, float *restrict data, uint32_t *restrict indices, uint32_t *restrict indptr, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u8 CSC1D f32 */
int bslz4_csc1d_u8_kcb_sse42(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint8_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, const float *restrict csc_flat, const uint32_t *restrict csc_first_bin, int csc_entries_per_pixel, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u16 basic */
int bslz4_u16_kcb_sse42(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint16_t *restrict output, uint32_t *restrict output_adr, int threshold, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u16 CSC f32 */
int bslz4_csc_u16_kcb_sse42(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint16_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, float *restrict data, uint32_t *restrict indices, uint32_t *restrict indptr, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u16 CSC1D f32 */
int bslz4_csc1d_u16_kcb_sse42(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint16_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, const float *restrict csc_flat, const uint32_t *restrict csc_first_bin, int csc_entries_per_pixel, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u32 basic */
int bslz4_u32_kcb_sse42(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint32_t *restrict output, uint32_t *restrict output_adr, int threshold, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u32 CSC f32 */
int bslz4_csc_u32_kcb_sse42(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint32_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, float *restrict data, uint32_t *restrict indices, uint32_t *restrict indptr, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u32 CSC1D f32 */
int bslz4_csc1d_u32_kcb_sse42(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint32_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, const float *restrict csc_flat, const uint32_t *restrict csc_first_bin, int csc_entries_per_pixel, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* =============================================================================
 * ZSTD engine x KCB backend
 * =============================================================================

/* u8 basic */
int bszstd_u8_kcb_avx512(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint8_t *restrict output, uint32_t *restrict output_adr, int threshold, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u8 CSC f32 */
int bszstd_csc_u8_kcb_avx512(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint8_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, float *restrict data, uint32_t *restrict indices, uint32_t *restrict indptr, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u8 CSC1D f32 */
int bszstd_csc1d_u8_kcb_avx512(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint8_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, const float *restrict csc_flat, const uint32_t *restrict csc_first_bin, int csc_entries_per_pixel, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u16 basic */
int bszstd_u16_kcb_avx512(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint16_t *restrict output, uint32_t *restrict output_adr, int threshold, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u16 CSC f32 */
int bszstd_csc_u16_kcb_avx512(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint16_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, float *restrict data, uint32_t *restrict indices, uint32_t *restrict indptr, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u16 CSC1D f32 */
int bszstd_csc1d_u16_kcb_avx512(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint16_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, const float *restrict csc_flat, const uint32_t *restrict csc_first_bin, int csc_entries_per_pixel, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u32 basic */
int bszstd_u32_kcb_avx512(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint32_t *restrict output, uint32_t *restrict output_adr, int threshold, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u32 CSC f32 */
int bszstd_csc_u32_kcb_avx512(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint32_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, float *restrict data, uint32_t *restrict indices, uint32_t *restrict indptr, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u32 CSC1D f32 */
int bszstd_csc1d_u32_kcb_avx512(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint32_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, const float *restrict csc_flat, const uint32_t *restrict csc_first_bin, int csc_entries_per_pixel, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u8 basic */
int bszstd_u8_kcb_avx2(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint8_t *restrict output, uint32_t *restrict output_adr, int threshold, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u8 CSC f32 */
int bszstd_csc_u8_kcb_avx2(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint8_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, float *restrict data, uint32_t *restrict indices, uint32_t *restrict indptr, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u8 CSC1D f32 */
int bszstd_csc1d_u8_kcb_avx2(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint8_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, const float *restrict csc_flat, const uint32_t *restrict csc_first_bin, int csc_entries_per_pixel, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u16 basic */
int bszstd_u16_kcb_avx2(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint16_t *restrict output, uint32_t *restrict output_adr, int threshold, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u16 CSC f32 */
int bszstd_csc_u16_kcb_avx2(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint16_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, float *restrict data, uint32_t *restrict indices, uint32_t *restrict indptr, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u16 CSC1D f32 */
int bszstd_csc1d_u16_kcb_avx2(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint16_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, const float *restrict csc_flat, const uint32_t *restrict csc_first_bin, int csc_entries_per_pixel, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u32 basic */
int bszstd_u32_kcb_avx2(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint32_t *restrict output, uint32_t *restrict output_adr, int threshold, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u32 CSC f32 */
int bszstd_csc_u32_kcb_avx2(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint32_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, float *restrict data, uint32_t *restrict indices, uint32_t *restrict indptr, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u32 CSC1D f32 */
int bszstd_csc1d_u32_kcb_avx2(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint32_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, const float *restrict csc_flat, const uint32_t *restrict csc_first_bin, int csc_entries_per_pixel, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u8 basic */
int bszstd_u8_kcb_sse42(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint8_t *restrict output, uint32_t *restrict output_adr, int threshold, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u8 CSC f32 */
int bszstd_csc_u8_kcb_sse42(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint8_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, float *restrict data, uint32_t *restrict indices, uint32_t *restrict indptr, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u8 CSC1D f32 */
int bszstd_csc1d_u8_kcb_sse42(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint8_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, const float *restrict csc_flat, const uint32_t *restrict csc_first_bin, int csc_entries_per_pixel, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u16 basic */
int bszstd_u16_kcb_sse42(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint16_t *restrict output, uint32_t *restrict output_adr, int threshold, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u16 CSC f32 */
int bszstd_csc_u16_kcb_sse42(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint16_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, float *restrict data, uint32_t *restrict indices, uint32_t *restrict indptr, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u16 CSC1D f32 */
int bszstd_csc1d_u16_kcb_sse42(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint16_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, const float *restrict csc_flat, const uint32_t *restrict csc_first_bin, int csc_entries_per_pixel, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u32 basic */
int bszstd_u32_kcb_sse42(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint32_t *restrict output, uint32_t *restrict output_adr, int threshold, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u32 CSC f32 */
int bszstd_csc_u32_kcb_sse42(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint32_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, float *restrict data, uint32_t *restrict indices, uint32_t *restrict indptr, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

/* u32 CSC1D f32 */
int bszstd_csc1d_u32_kcb_sse42(const uint8_t *restrict compressed, int compressed_length, const uint8_t *restrict mask, int NIJ, uint32_t *restrict outpx, uint32_t *restrict output_adr, int threshold, double *restrict output, int nout_total, const float *restrict csc_flat, const uint32_t *restrict csc_first_bin, int csc_entries_per_pixel, const int64_t *restrict chunk_offsets, const int32_t *restrict chunk_lengths, int nchunks, int32_t *restrict npx_per_chunk);

#endif /* BS_FUNCTIONS_H */
