/* bs_master.c - bitshuffle sparse decompression master compilation unit.
 *
 * AUTO-GENERATED by generate_bslz4.py -- DO NOT EDIT BY HAND.
 *
 * Compiled multiple times with different -D flags:
 *   -DKERNEL_SUFFIX=_kcb_avx512  (or _bs_sse42, etc.)
 *   -DUSE_KCB  (or leave undefined for bitshuffle-core)
 *   -DUSE_ZSTD (or leave undefined for LZ4)
 *
 * Each compilation includes bs_sparse_tmpl.c 3 times (once per pixel type)
 * and bs_sparse_csc_tmpl.c 12 times (3 pixel types x 4 CSC data types).
 * Generates  3 basic + 12 CSC = 15 functions per compilation unit.
 */

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <limits.h>
#include <stdio.h>

/* --------------------------------------------------------------------------
 * Engine selection
 * -------------------------------------------------------------------------- */

#ifdef USE_ZSTD
#define FN_PREFIX bszstd
#include "zstd/lib/zstd.h"
#define BS_DECOMPRESS(src, srcSize, dst, dstSize) \
    ((int)ZSTD_decompress((dst), (size_t)(dstSize), (src), (size_t)(srcSize)))
#else
#define FN_PREFIX bslz4
#include "lz4/lib/lz4.h"
#define BS_DECOMPRESS(src, srcSize, dst, dstSize) \
    LZ4_decompress_safe((const char*)(src), (char*)(dst), (srcSize), (dstSize))
#endif

/* --------------------------------------------------------------------------
 * Bitshuffle backend selection
 * -------------------------------------------------------------------------- */

#ifdef USE_KCB
#include "kcb/src/bitshuffle.h"
#else
int64_t bshuf_untrans_bit_elem(const void* in, void* out, const size_t size,
        const size_t elem_size);
#endif

/* --------------------------------------------------------------------------
 * Utility macros
 * -------------------------------------------------------------------------- */

#define READ32BE(p) \
  ((uint32_t)(255 & (p)[0]) << 24 |\
   (uint32_t)(255 & (p)[1]) << 16 |\
   (uint32_t)(255 & (p)[2]) <<  8 |\
   (uint32_t)(255 & (p)[3]))

#define READ64BE(p) \
  ((uint64_t)(255 & (p)[0]) << 56 |\
   (uint64_t)(255 & (p)[1]) << 48 |\
   (uint64_t)(255 & (p)[2]) << 40 |\
   (uint64_t)(255 & (p)[3]) << 32 |\
   (uint64_t)(255 & (p)[4]) << 24 |\
   (uint64_t)(255 & (p)[5]) << 16 |\
   (uint64_t)(255 & (p)[6]) <<  8 |\
   (uint64_t)(255 & (p)[7]))

#ifndef unlikely
#ifdef _MSC_VER
#define unlikely
#else
#define unlikely(expr) (__builtin_expect(!!(expr), 0))
#endif
#endif

#define BLK 8192

#define CAT_I(a,b) a##b
#define CAT(a,b) CAT_I(a,b)
#define CAT3(a,b,c) CAT(CAT(a,b),c)
#define CAT4(a,b,c,d) CAT(CAT3(a,b,c),d)

#ifndef KERNEL_SUFFIX
#define KERNEL_SUFFIX _sse42
#endif

#define FULL_SUFFIX KERNEL_SUFFIX


/* ================================================================
 * Pixel type: uint8_t (NB=1)
 * ================================================================ */

#define DATATYPE uint8_t
#define DT_SHORT u8
#define NB 1

#define KERNEL_FN CAT3(FN_PREFIX, _, CAT(DT_SHORT, FULL_SUFFIX))
#include "bs_sparse_tmpl.c"

#define CSC_DATA_T float
#define CSC_SUM_T double
#define KERNEL_CSC_FN CAT3(FN_PREFIX, _csc_, CAT(DT_SHORT, FULL_SUFFIX))
#include "bs_sparse_csc_tmpl.c"
#define CSC_DATA_T uint8_t
#define CSC_SUM_T uint64_t
#define KERNEL_CSC_FN CAT4(FN_PREFIX, _csc_, CAT3(DT_SHORT, _, cu8), FULL_SUFFIX)
#include "bs_sparse_csc_tmpl.c"
#define CSC_DATA_T uint16_t
#define CSC_SUM_T uint64_t
#define KERNEL_CSC_FN CAT4(FN_PREFIX, _csc_, CAT3(DT_SHORT, _, cu16), FULL_SUFFIX)
#include "bs_sparse_csc_tmpl.c"
#define CSC_DATA_T uint32_t
#define CSC_SUM_T uint64_t
#define KERNEL_CSC_FN CAT4(FN_PREFIX, _csc_, CAT3(DT_SHORT, _, cu32), FULL_SUFFIX)
#include "bs_sparse_csc_tmpl.c"

#undef DATATYPE
#undef DT_SHORT
#undef NB
#undef KERNEL_FN
#undef CSC_DATA_T
#undef CSC_SUM_T
#undef KERNEL_CSC_FN

/* ================================================================
 * Pixel type: uint16_t (NB=2)
 * ================================================================ */

#define DATATYPE uint16_t
#define DT_SHORT u16
#define NB 2

#define KERNEL_FN CAT3(FN_PREFIX, _, CAT(DT_SHORT, FULL_SUFFIX))
#include "bs_sparse_tmpl.c"

#define CSC_DATA_T float
#define CSC_SUM_T double
#define KERNEL_CSC_FN CAT3(FN_PREFIX, _csc_, CAT(DT_SHORT, FULL_SUFFIX))
#include "bs_sparse_csc_tmpl.c"
#define CSC_DATA_T uint8_t
#define CSC_SUM_T uint64_t
#define KERNEL_CSC_FN CAT4(FN_PREFIX, _csc_, CAT3(DT_SHORT, _, cu8), FULL_SUFFIX)
#include "bs_sparse_csc_tmpl.c"
#define CSC_DATA_T uint16_t
#define CSC_SUM_T uint64_t
#define KERNEL_CSC_FN CAT4(FN_PREFIX, _csc_, CAT3(DT_SHORT, _, cu16), FULL_SUFFIX)
#include "bs_sparse_csc_tmpl.c"
#define CSC_DATA_T uint32_t
#define CSC_SUM_T uint64_t
#define KERNEL_CSC_FN CAT4(FN_PREFIX, _csc_, CAT3(DT_SHORT, _, cu32), FULL_SUFFIX)
#include "bs_sparse_csc_tmpl.c"

#undef DATATYPE
#undef DT_SHORT
#undef NB
#undef KERNEL_FN
#undef CSC_DATA_T
#undef CSC_SUM_T
#undef KERNEL_CSC_FN

/* ================================================================
 * Pixel type: uint32_t (NB=4)
 * ================================================================ */

#define DATATYPE uint32_t
#define DT_SHORT u32
#define NB 4

#define KERNEL_FN CAT3(FN_PREFIX, _, CAT(DT_SHORT, FULL_SUFFIX))
#include "bs_sparse_tmpl.c"

#define CSC_DATA_T float
#define CSC_SUM_T double
#define KERNEL_CSC_FN CAT3(FN_PREFIX, _csc_, CAT(DT_SHORT, FULL_SUFFIX))
#include "bs_sparse_csc_tmpl.c"
#define CSC_DATA_T uint8_t
#define CSC_SUM_T uint64_t
#define KERNEL_CSC_FN CAT4(FN_PREFIX, _csc_, CAT3(DT_SHORT, _, cu8), FULL_SUFFIX)
#include "bs_sparse_csc_tmpl.c"
#define CSC_DATA_T uint16_t
#define CSC_SUM_T uint64_t
#define KERNEL_CSC_FN CAT4(FN_PREFIX, _csc_, CAT3(DT_SHORT, _, cu16), FULL_SUFFIX)
#include "bs_sparse_csc_tmpl.c"
#define CSC_DATA_T uint32_t
#define CSC_SUM_T uint64_t
#define KERNEL_CSC_FN CAT4(FN_PREFIX, _csc_, CAT3(DT_SHORT, _, cu32), FULL_SUFFIX)
#include "bs_sparse_csc_tmpl.c"

#undef DATATYPE
#undef DT_SHORT
#undef NB
#undef KERNEL_FN
#undef CSC_DATA_T
#undef CSC_SUM_T
#undef KERNEL_CSC_FN
